// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/surfacers/stackdriver/proto/config.proto

package cloudprober_surfacer_stackdriver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SurfacerConf struct {
	Batch                *bool    `protobuf:"varint,1,opt,name=batch,def=1" json:"batch,omitempty"`
	BatchSize            *uint64  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,def=200" json:"batch_size,omitempty"`
	BatchTimerSec        *uint64  `protobuf:"varint,3,opt,name=batch_timer_sec,json=batchTimerSec,def=10" json:"batch_timer_sec,omitempty"`
	MonitoringUrl        *string  `protobuf:"bytes,5,opt,name=monitoring_url,json=monitoringUrl,def=custom.googleapis.com/cloudprober/" json:"monitoring_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurfacerConf) Reset()         { *m = SurfacerConf{} }
func (m *SurfacerConf) String() string { return proto.CompactTextString(m) }
func (*SurfacerConf) ProtoMessage()    {}
func (*SurfacerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_a11f493ce0b9664a, []int{0}
}
func (m *SurfacerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurfacerConf.Unmarshal(m, b)
}
func (m *SurfacerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurfacerConf.Marshal(b, m, deterministic)
}
func (dst *SurfacerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurfacerConf.Merge(dst, src)
}
func (m *SurfacerConf) XXX_Size() int {
	return xxx_messageInfo_SurfacerConf.Size(m)
}
func (m *SurfacerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_SurfacerConf.DiscardUnknown(m)
}

var xxx_messageInfo_SurfacerConf proto.InternalMessageInfo

const Default_SurfacerConf_Batch bool = true
const Default_SurfacerConf_BatchSize uint64 = 200
const Default_SurfacerConf_BatchTimerSec uint64 = 10
const Default_SurfacerConf_MonitoringUrl string = "custom.googleapis.com/cloudprober/"

func (m *SurfacerConf) GetBatch() bool {
	if m != nil && m.Batch != nil {
		return *m.Batch
	}
	return Default_SurfacerConf_Batch
}

func (m *SurfacerConf) GetBatchSize() uint64 {
	if m != nil && m.BatchSize != nil {
		return *m.BatchSize
	}
	return Default_SurfacerConf_BatchSize
}

func (m *SurfacerConf) GetBatchTimerSec() uint64 {
	if m != nil && m.BatchTimerSec != nil {
		return *m.BatchTimerSec
	}
	return Default_SurfacerConf_BatchTimerSec
}

func (m *SurfacerConf) GetMonitoringUrl() string {
	if m != nil && m.MonitoringUrl != nil {
		return *m.MonitoringUrl
	}
	return Default_SurfacerConf_MonitoringUrl
}

func init() {
	proto.RegisterType((*SurfacerConf)(nil), "cloudprober.surfacer.stackdriver.SurfacerConf")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/surfacers/stackdriver/proto/config.proto", fileDescriptor_config_a11f493ce0b9664a)
}

var fileDescriptor_config_a11f493ce0b9664a = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe5, 0xfe, 0x91, 0xa8, 0x45, 0x41, 0xf2, 0x14, 0x31, 0x45, 0x99, 0x22, 0x06, 0x3b,
	0x30, 0x66, 0x85, 0x85, 0x35, 0x81, 0x39, 0x4a, 0xdc, 0x8b, 0x6b, 0x91, 0xe4, 0xa2, 0xb3, 0x8d,
	0xa0, 0xdf, 0x8f, 0xef, 0x85, 0x70, 0x41, 0xcd, 0x76, 0xf7, 0x7e, 0xef, 0xb7, 0x3c, 0xfe, 0x6c,
	0xac, 0x3f, 0x86, 0x4e, 0x6a, 0x1c, 0xd5, 0x17, 0x7c, 0x7a, 0xa5, 0x07, 0x0c, 0x87, 0x99, 0xb0,
	0x03, 0x52, 0x2e, 0x50, 0xdf, 0x6a, 0x20, 0xa7, 0x9c, 0x6f, 0xf5, 0xfb, 0x81, 0xec, 0x07, 0x90,
	0x9a, 0x09, 0x3d, 0x2a, 0x8d, 0x53, 0x6f, 0x8d, 0x8c, 0x8f, 0x48, 0x17, 0x96, 0xfc, 0xb7, 0xe4,
	0x42, 0xca, 0xbe, 0x19, 0xbf, 0xae, 0xff, 0xc0, 0x13, 0x4e, 0xbd, 0xb8, 0xe3, 0xdb, 0xae, 0xf5,
	0xfa, 0x98, 0xb0, 0x94, 0xe5, 0x57, 0xe5, 0xc6, 0x53, 0x80, 0xea, 0x1c, 0x89, 0x8c, 0xf3, 0x78,
	0x34, 0xce, 0x9e, 0x20, 0x59, 0xa5, 0x2c, 0xdf, 0x94, 0xeb, 0xc7, 0xa2, 0xa8, 0x76, 0x31, 0xae,
	0xed, 0x09, 0xc4, 0x3d, 0xbf, 0x3d, 0x77, 0xbc, 0x1d, 0x81, 0x1a, 0x07, 0x3a, 0x59, 0xc7, 0xe2,
	0xea, 0xa1, 0xa8, 0xf6, 0x11, 0xbd, 0xfe, 0x92, 0x1a, 0xb4, 0x78, 0xe1, 0x37, 0x23, 0x4e, 0xd6,
	0x23, 0xd9, 0xc9, 0x34, 0x81, 0x86, 0x64, 0x9b, 0xb2, 0x7c, 0x57, 0x66, 0x3a, 0x38, 0x8f, 0xa3,
	0x34, 0x88, 0x66, 0x80, 0x76, 0xb6, 0x2e, 0xee, 0xb0, 0x9c, 0xa0, 0xda, 0x5f, 0xcc, 0x37, 0x1a,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x68, 0x9b, 0x30, 0x30, 0x01, 0x00, 0x00,
}
