// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/config/proto/config.proto

package cloudprober

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/yext/cloudprober/probes/proto"
import proto3 "github.com/yext/cloudprober/servers/proto"
import proto2 "github.com/yext/cloudprober/surfacers/proto"
import proto6 "github.com/yext/cloudprober/targets/proto"
import proto4 "github.com/yext/cloudprober/targets/rds/server/proto"
import proto5 "github.com/yext/cloudprober/targets/rtc/rtcreporter/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ProberConfig struct {
	// Probes to run.
	Probe []*proto1.ProbeDef `protobuf:"bytes,1,rep,name=probe" json:"probe,omitempty"`
	// Surfacers are used to export probe results for further processing.
	// If no surfacer is configured, a prometheus and a file surfacer are
	// initialized:
	//  - Prometheus makes probe results available at http://<host>:9313/metrics.
	//  - File surfacer writes results to stdout.
	//
	// You can disable default surfacers (in case you want no surfacer at all), by
	// adding the following to your config:
	//   surfacer {}
	Surfacer []*proto2.SurfacerDef `protobuf:"bytes,2,rep,name=surfacer" json:"surfacer,omitempty"`
	// Servers to run inside cloudprober. These servers can serve as targets for
	// other probes.
	Server []*proto3.ServerDef `protobuf:"bytes,3,rep,name=server" json:"server,omitempty"`
	// Resource discovery server
	RdsServer *proto4.ServerConf `protobuf:"bytes,95,opt,name=rds_server,json=rdsServer" json:"rds_server,omitempty"`
	// Port for the default HTTP server. This port is also used for prometheus
	// exporter (URL /metrics). Default port is 9313. If not specified in the
	// config, default port can be overridden by the environment variable
	// CLOUDPROBER_PORT.
	Port *int32 `protobuf:"varint,96,opt,name=port" json:"port,omitempty"`
	// Host for the default HTTP server. Default listens on all addresses. If not
	// specified in the config, default port can be overridden by the environment
	// variable CLOUDPROBER_HOST.
	Host *string `protobuf:"bytes,101,opt,name=host" json:"host,omitempty"`
	// Probes are staggered across time to avoid executing all of them at the
	// same time. This behavior can be disabled by setting the following option
	// to true.
	DisableJitter *bool `protobuf:"varint,102,opt,name=disable_jitter,json=disableJitter,def=0" json:"disable_jitter,omitempty"`
	// How often to export system variables. To learn more about system variables:
	// http://godoc.org/github.com/google/cloudprober/sysvars.
	SysvarsIntervalMsec *int32 `protobuf:"varint,97,opt,name=sysvars_interval_msec,json=sysvarsIntervalMsec,def=10000" json:"sysvars_interval_msec,omitempty"`
	// Variables specified in this environment variable are exported as it is.
	// This is specifically useful to export information about system environment,
	// for example, docker image tag/digest-id, OS version etc. See
	// tools/cloudprober_startup.sh in the cloudprober directory for an example on
	// how to use these variables.
	SysvarsEnvVar *string `protobuf:"bytes,98,opt,name=sysvars_env_var,json=sysvarsEnvVar,def=SYSVARS" json:"sysvars_env_var,omitempty"`
	// Options for RTC reporter. RTC reporter reports information about the
	// current instance to a Runtime Config (RTC). This is useful if you want your
	// instance to be dynamically discoverable through RTC targets. This is
	// disabled by default.
	RtcReportOptions *proto5.RtcReportOptions `protobuf:"bytes,99,opt,name=rtc_report_options,json=rtcReportOptions" json:"rtc_report_options,omitempty"`
	// Global targets options. Per-probe options are specified within the probe
	// stanza.
	GlobalTargetsOptions *proto6.GlobalTargetsOptions `protobuf:"bytes,100,opt,name=global_targets_options,json=globalTargetsOptions" json:"global_targets_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ProberConfig) Reset()         { *m = ProberConfig{} }
func (m *ProberConfig) String() string { return proto.CompactTextString(m) }
func (*ProberConfig) ProtoMessage()    {}
func (*ProberConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_e465de6da1599de7, []int{0}
}
func (m *ProberConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProberConfig.Unmarshal(m, b)
}
func (m *ProberConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProberConfig.Marshal(b, m, deterministic)
}
func (dst *ProberConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProberConfig.Merge(dst, src)
}
func (m *ProberConfig) XXX_Size() int {
	return xxx_messageInfo_ProberConfig.Size(m)
}
func (m *ProberConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProberConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProberConfig proto.InternalMessageInfo

const Default_ProberConfig_DisableJitter bool = false
const Default_ProberConfig_SysvarsIntervalMsec int32 = 10000
const Default_ProberConfig_SysvarsEnvVar string = "SYSVARS"

func (m *ProberConfig) GetProbe() []*proto1.ProbeDef {
	if m != nil {
		return m.Probe
	}
	return nil
}

func (m *ProberConfig) GetSurfacer() []*proto2.SurfacerDef {
	if m != nil {
		return m.Surfacer
	}
	return nil
}

func (m *ProberConfig) GetServer() []*proto3.ServerDef {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ProberConfig) GetRdsServer() *proto4.ServerConf {
	if m != nil {
		return m.RdsServer
	}
	return nil
}

func (m *ProberConfig) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ProberConfig) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *ProberConfig) GetDisableJitter() bool {
	if m != nil && m.DisableJitter != nil {
		return *m.DisableJitter
	}
	return Default_ProberConfig_DisableJitter
}

func (m *ProberConfig) GetSysvarsIntervalMsec() int32 {
	if m != nil && m.SysvarsIntervalMsec != nil {
		return *m.SysvarsIntervalMsec
	}
	return Default_ProberConfig_SysvarsIntervalMsec
}

func (m *ProberConfig) GetSysvarsEnvVar() string {
	if m != nil && m.SysvarsEnvVar != nil {
		return *m.SysvarsEnvVar
	}
	return Default_ProberConfig_SysvarsEnvVar
}

func (m *ProberConfig) GetRtcReportOptions() *proto5.RtcReportOptions {
	if m != nil {
		return m.RtcReportOptions
	}
	return nil
}

func (m *ProberConfig) GetGlobalTargetsOptions() *proto6.GlobalTargetsOptions {
	if m != nil {
		return m.GlobalTargetsOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*ProberConfig)(nil), "cloudprober.ProberConfig")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/config/proto/config.proto", fileDescriptor_config_e465de6da1599de7)
}

var fileDescriptor_config_e465de6da1599de7 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdb, 0x8b, 0xd4, 0x30,
	0x14, 0xc6, 0xa9, 0x6b, 0x75, 0x37, 0xe3, 0xaa, 0xc4, 0x0b, 0x61, 0x11, 0xa9, 0xfa, 0x52, 0x41,
	0xda, 0xd9, 0x01, 0x57, 0x1d, 0xf0, 0x61, 0xbd, 0x20, 0x2a, 0xa2, 0xa4, 0xb2, 0xe0, 0x53, 0x4c,
	0xd3, 0xb4, 0x5b, 0xe9, 0x36, 0xc3, 0x49, 0xa6, 0xb8, 0x8f, 0xfe, 0xe7, 0xd2, 0x24, 0x1d, 0x66,
	0xa4, 0x0e, 0xf3, 0x30, 0xf4, 0xdc, 0x7e, 0xdf, 0x97, 0xe4, 0x0c, 0x7a, 0x5e, 0xd5, 0xe6, 0x7c,
	0x99, 0x27, 0x42, 0x5d, 0xa4, 0x97, 0xf2, 0xb7, 0x49, 0x45, 0xa3, 0x96, 0xc5, 0x02, 0x54, 0x2e,
	0x21, 0x15, 0xaa, 0x2d, 0xeb, 0x2a, 0x5d, 0x80, 0x32, 0xca, 0x27, 0x89, 0x4d, 0xf0, 0x64, 0x6d,
	0xec, 0x68, 0xab, 0x86, 0xfd, 0xe8, 0x11, 0x8d, 0xa3, 0x93, 0x6d, 0x98, 0x96, 0xd0, 0x49, 0x18,
	0xe5, 0x5e, 0x6c, 0xe3, 0x0c, 0x87, 0x4a, 0x9a, 0x81, 0xf3, 0x99, 0x07, 0x5f, 0x6e, 0x35, 0x5c,
	0x42, 0xc9, 0xc5, 0x7f, 0x2c, 0x4f, 0x77, 0xb1, 0x84, 0x42, 0xfb, 0x63, 0x8f, 0x49, 0x7c, 0xde,
	0x49, 0xc2, 0x88, 0xfe, 0x07, 0x72, 0xa1, 0xc0, 0xac, 0x74, 0xd6, 0x2a, 0x4e, 0xec, 0xf1, 0x9f,
	0x10, 0xdd, 0xf8, 0x66, 0xd1, 0xb7, 0xd6, 0x03, 0xcf, 0x50, 0x68, 0xa5, 0x48, 0x10, 0xed, 0xc5,
	0x93, 0xd9, 0x83, 0x64, 0x4d, 0x3d, 0x71, 0x2b, 0x48, 0x2c, 0xf0, 0x4e, 0x96, 0xd4, 0x8d, 0xe2,
	0xd7, 0x68, 0x7f, 0xb8, 0x34, 0xb9, 0x62, 0xb1, 0x47, 0x1b, 0xd8, 0xd0, 0x4c, 0x32, 0x1f, 0xf4,
	0xec, 0x0a, 0xc1, 0x27, 0xe8, 0x9a, 0xbb, 0x2d, 0xd9, 0xb3, 0xf0, 0xc3, 0x4d, 0xd8, 0xed, 0x2f,
	0xc9, 0xec, 0xb7, 0x27, 0xfd, 0x34, 0x7e, 0x83, 0x10, 0x14, 0x9a, 0x79, 0x96, 0x45, 0x41, 0x3c,
	0x99, 0x3d, 0xd9, 0x60, 0x87, 0xad, 0x41, 0x31, 0xf0, 0xfd, 0x2d, 0xe9, 0x01, 0x14, 0xda, 0xa5,
	0x18, 0xa3, 0xab, 0xfd, 0x7b, 0x90, 0x9f, 0x51, 0x10, 0x87, 0xd4, 0xc6, 0x7d, 0xed, 0x5c, 0x69,
	0x43, 0x64, 0x14, 0xc4, 0x07, 0xd4, 0xc6, 0xf8, 0x19, 0xba, 0x59, 0xd4, 0x9a, 0xe7, 0x8d, 0x64,
	0xbf, 0x6a, 0x63, 0x24, 0x90, 0x32, 0x0a, 0xe2, 0xfd, 0x79, 0x58, 0xf2, 0x46, 0x4b, 0x7a, 0xe8,
	0x9b, 0x9f, 0x6c, 0x0f, 0xbf, 0x42, 0xf7, 0xf4, 0xa5, 0xee, 0x38, 0x68, 0x56, 0xb7, 0x46, 0x42,
	0xc7, 0x1b, 0x76, 0xa1, 0xa5, 0x20, 0xbc, 0xb7, 0x99, 0x87, 0xc7, 0xd3, 0xe9, 0x74, 0x4a, 0xef,
	0xf8, 0x99, 0x8f, 0x7e, 0xe4, 0x8b, 0x96, 0x02, 0xa7, 0xe8, 0xd6, 0x80, 0xca, 0xb6, 0x63, 0x1d,
	0x07, 0x92, 0xf7, 0xe7, 0x98, 0x5f, 0xcf, 0x7e, 0x64, 0x67, 0xa7, 0x34, 0xa3, 0x87, 0xbe, 0xff,
	0xbe, 0xed, 0xce, 0x38, 0x60, 0x86, 0x30, 0x18, 0xc1, 0xdc, 0x5e, 0x99, 0x5a, 0x98, 0x5a, 0xb5,
	0x9a, 0x08, 0xfb, 0x1a, 0xc7, 0xe3, 0xaf, 0xb1, 0xf6, 0x2f, 0xa0, 0x46, 0x50, 0x1b, 0x7f, 0x75,
	0x20, 0xbd, 0x0d, 0xff, 0x54, 0x30, 0x43, 0xf7, 0xab, 0x46, 0xe5, 0xbc, 0x61, 0x5e, 0x60, 0x65,
	0x52, 0x58, 0x93, 0xa7, 0xa3, 0x26, 0x1f, 0x2c, 0xf2, 0xdd, 0x65, 0x83, 0xf8, 0xdd, 0x6a, 0xa4,
	0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x51, 0xeb, 0x7f, 0x3a, 0x04, 0x00, 0x00,
}
