// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/probes/proto/config.proto

package cloudprober_probes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto2 "github.com/yext/cloudprober/metrics/proto"
import proto6 "github.com/yext/cloudprober/probes/dns/proto"
import proto7 "github.com/yext/cloudprober/probes/external/proto"
import proto5 "github.com/yext/cloudprober/probes/http/proto"
import proto4 "github.com/yext/cloudprober/probes/ping/proto"
import proto8 "github.com/yext/cloudprober/probes/udp/proto"
import proto9 "github.com/yext/cloudprober/probes/udplistener/proto"
import proto1 "github.com/yext/cloudprober/targets/proto"
import proto3 "github.com/yext/cloudprober/validators/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ProbeDef_Type int32

const (
	ProbeDef_PING         ProbeDef_Type = 0
	ProbeDef_HTTP         ProbeDef_Type = 1
	ProbeDef_DNS          ProbeDef_Type = 2
	ProbeDef_EXTERNAL     ProbeDef_Type = 3
	ProbeDef_UDP          ProbeDef_Type = 4
	ProbeDef_UDP_LISTENER ProbeDef_Type = 5
	// One of the extension probe types. See "extensions" below for more
	// details.
	ProbeDef_EXTENSION ProbeDef_Type = 98
	// USER_DEFINED probe type is for a one off probe that you want to compile
	// into cloudprober, but you don't expect it to be reused. If you expect
	// it to be reused, you should consider adding it using the extensions
	// mechanism.
	ProbeDef_USER_DEFINED ProbeDef_Type = 99
)

var ProbeDef_Type_name = map[int32]string{
	0:  "PING",
	1:  "HTTP",
	2:  "DNS",
	3:  "EXTERNAL",
	4:  "UDP",
	5:  "UDP_LISTENER",
	98: "EXTENSION",
	99: "USER_DEFINED",
}
var ProbeDef_Type_value = map[string]int32{
	"PING":         0,
	"HTTP":         1,
	"DNS":          2,
	"EXTERNAL":     3,
	"UDP":          4,
	"UDP_LISTENER": 5,
	"EXTENSION":    98,
	"USER_DEFINED": 99,
}

func (x ProbeDef_Type) Enum() *ProbeDef_Type {
	p := new(ProbeDef_Type)
	*p = x
	return p
}
func (x ProbeDef_Type) String() string {
	return proto.EnumName(ProbeDef_Type_name, int32(x))
}
func (x *ProbeDef_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProbeDef_Type_value, data, "ProbeDef_Type")
	if err != nil {
		return err
	}
	*x = ProbeDef_Type(value)
	return nil
}
func (ProbeDef_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_4592f190be15414f, []int{0, 0}
}

type ProbeDef struct {
	Name *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type *ProbeDef_Type `protobuf:"varint,2,req,name=type,enum=cloudprober.probes.ProbeDef_Type" json:"type,omitempty"`
	// Which machines this probe should run on. If defined, cloudprober will run
	// this probe only if machine's hostname matches this value.
	RunOn *string `protobuf:"bytes,3,opt,name=run_on,json=runOn" json:"run_on,omitempty"`
	// Interval between two probes
	IntervalMsec *int32 `protobuf:"varint,4,opt,name=interval_msec,json=intervalMsec,def=2000" json:"interval_msec,omitempty"`
	// Timeout for each probe
	TimeoutMsec *int32 `protobuf:"varint,5,opt,name=timeout_msec,json=timeoutMsec,def=1000" json:"timeout_msec,omitempty"`
	// Targets for the probe
	Targets *proto1.TargetsDef `protobuf:"bytes,6,req,name=targets" json:"targets,omitempty"`
	// Latency distribution. If specified, latency is stored as a distribution.
	LatencyDistribution *proto2.Dist `protobuf:"bytes,7,opt,name=latency_distribution,json=latencyDistribution" json:"latency_distribution,omitempty"`
	// Latency unit. Any string that's parseable by time.ParseDuration.
	// Valid values: "ns", "us" (or "µs"), "ms", "s", "m", "h".
	LatencyUnit *string `protobuf:"bytes,8,opt,name=latency_unit,json=latencyUnit,def=us" json:"latency_unit,omitempty"`
	// Validators are in experimental phase right now and can change at any time.
	// NOTE: Only PING, HTTP and DNS probes support validators.
	Validator []*proto3.Validator `protobuf:"bytes,9,rep,name=validator" json:"validator,omitempty"`
	// Set the source IP to send packets from, either by providing an IP address
	// directly, or a network interface.
	// NOTE: Only PING and HTTP probes support this field right now.
	//
	// Types that are valid to be assigned to SourceIpConfig:
	//	*ProbeDef_SourceIp
	//	*ProbeDef_SourceInterface
	SourceIpConfig isProbeDef_SourceIpConfig `protobuf_oneof:"source_ip_config"`
	// Types that are valid to be assigned to Probe:
	//	*ProbeDef_PingProbe
	//	*ProbeDef_HttpProbe
	//	*ProbeDef_DnsProbe
	//	*ProbeDef_ExternalProbe
	//	*ProbeDef_UdpProbe
	//	*ProbeDef_UdpListenerProbe
	//	*ProbeDef_UserDefinedProbe
	Probe                        isProbeDef_Probe `protobuf_oneof:"probe"`
	DebugOptions                 *DebugOptions    `protobuf:"bytes,100,opt,name=debug_options,json=debugOptions" json:"debug_options,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}         `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *ProbeDef) Reset()         { *m = ProbeDef{} }
func (m *ProbeDef) String() string { return proto.CompactTextString(m) }
func (*ProbeDef) ProtoMessage()    {}
func (*ProbeDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_4592f190be15414f, []int{0}
}

var extRange_ProbeDef = []proto.ExtensionRange{
	{Start: 200, End: 536870911},
}

func (*ProbeDef) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ProbeDef
}
func (m *ProbeDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeDef.Unmarshal(m, b)
}
func (m *ProbeDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeDef.Marshal(b, m, deterministic)
}
func (dst *ProbeDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeDef.Merge(dst, src)
}
func (m *ProbeDef) XXX_Size() int {
	return xxx_messageInfo_ProbeDef.Size(m)
}
func (m *ProbeDef) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeDef.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeDef proto.InternalMessageInfo

const Default_ProbeDef_IntervalMsec int32 = 2000
const Default_ProbeDef_TimeoutMsec int32 = 1000
const Default_ProbeDef_LatencyUnit string = "us"

type isProbeDef_SourceIpConfig interface {
	isProbeDef_SourceIpConfig()
}
type isProbeDef_Probe interface {
	isProbeDef_Probe()
}

type ProbeDef_SourceIp struct {
	SourceIp string `protobuf:"bytes,10,opt,name=source_ip,json=sourceIp,oneof"`
}
type ProbeDef_SourceInterface struct {
	SourceInterface string `protobuf:"bytes,11,opt,name=source_interface,json=sourceInterface,oneof"`
}
type ProbeDef_PingProbe struct {
	PingProbe *proto4.ProbeConf `protobuf:"bytes,20,opt,name=ping_probe,json=pingProbe,oneof"`
}
type ProbeDef_HttpProbe struct {
	HttpProbe *proto5.ProbeConf `protobuf:"bytes,21,opt,name=http_probe,json=httpProbe,oneof"`
}
type ProbeDef_DnsProbe struct {
	DnsProbe *proto6.ProbeConf `protobuf:"bytes,22,opt,name=dns_probe,json=dnsProbe,oneof"`
}
type ProbeDef_ExternalProbe struct {
	ExternalProbe *proto7.ProbeConf `protobuf:"bytes,23,opt,name=external_probe,json=externalProbe,oneof"`
}
type ProbeDef_UdpProbe struct {
	UdpProbe *proto8.ProbeConf `protobuf:"bytes,24,opt,name=udp_probe,json=udpProbe,oneof"`
}
type ProbeDef_UdpListenerProbe struct {
	UdpListenerProbe *proto9.ProbeConf `protobuf:"bytes,25,opt,name=udp_listener_probe,json=udpListenerProbe,oneof"`
}
type ProbeDef_UserDefinedProbe struct {
	UserDefinedProbe string `protobuf:"bytes,99,opt,name=user_defined_probe,json=userDefinedProbe,oneof"`
}

func (*ProbeDef_SourceIp) isProbeDef_SourceIpConfig()        {}
func (*ProbeDef_SourceInterface) isProbeDef_SourceIpConfig() {}
func (*ProbeDef_PingProbe) isProbeDef_Probe()                {}
func (*ProbeDef_HttpProbe) isProbeDef_Probe()                {}
func (*ProbeDef_DnsProbe) isProbeDef_Probe()                 {}
func (*ProbeDef_ExternalProbe) isProbeDef_Probe()            {}
func (*ProbeDef_UdpProbe) isProbeDef_Probe()                 {}
func (*ProbeDef_UdpListenerProbe) isProbeDef_Probe()         {}
func (*ProbeDef_UserDefinedProbe) isProbeDef_Probe()         {}

func (m *ProbeDef) GetSourceIpConfig() isProbeDef_SourceIpConfig {
	if m != nil {
		return m.SourceIpConfig
	}
	return nil
}
func (m *ProbeDef) GetProbe() isProbeDef_Probe {
	if m != nil {
		return m.Probe
	}
	return nil
}

func (m *ProbeDef) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProbeDef) GetType() ProbeDef_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProbeDef_PING
}

func (m *ProbeDef) GetRunOn() string {
	if m != nil && m.RunOn != nil {
		return *m.RunOn
	}
	return ""
}

func (m *ProbeDef) GetIntervalMsec() int32 {
	if m != nil && m.IntervalMsec != nil {
		return *m.IntervalMsec
	}
	return Default_ProbeDef_IntervalMsec
}

func (m *ProbeDef) GetTimeoutMsec() int32 {
	if m != nil && m.TimeoutMsec != nil {
		return *m.TimeoutMsec
	}
	return Default_ProbeDef_TimeoutMsec
}

func (m *ProbeDef) GetTargets() *proto1.TargetsDef {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ProbeDef) GetLatencyDistribution() *proto2.Dist {
	if m != nil {
		return m.LatencyDistribution
	}
	return nil
}

func (m *ProbeDef) GetLatencyUnit() string {
	if m != nil && m.LatencyUnit != nil {
		return *m.LatencyUnit
	}
	return Default_ProbeDef_LatencyUnit
}

func (m *ProbeDef) GetValidator() []*proto3.Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *ProbeDef) GetSourceIp() string {
	if x, ok := m.GetSourceIpConfig().(*ProbeDef_SourceIp); ok {
		return x.SourceIp
	}
	return ""
}

func (m *ProbeDef) GetSourceInterface() string {
	if x, ok := m.GetSourceIpConfig().(*ProbeDef_SourceInterface); ok {
		return x.SourceInterface
	}
	return ""
}

func (m *ProbeDef) GetPingProbe() *proto4.ProbeConf {
	if x, ok := m.GetProbe().(*ProbeDef_PingProbe); ok {
		return x.PingProbe
	}
	return nil
}

func (m *ProbeDef) GetHttpProbe() *proto5.ProbeConf {
	if x, ok := m.GetProbe().(*ProbeDef_HttpProbe); ok {
		return x.HttpProbe
	}
	return nil
}

func (m *ProbeDef) GetDnsProbe() *proto6.ProbeConf {
	if x, ok := m.GetProbe().(*ProbeDef_DnsProbe); ok {
		return x.DnsProbe
	}
	return nil
}

func (m *ProbeDef) GetExternalProbe() *proto7.ProbeConf {
	if x, ok := m.GetProbe().(*ProbeDef_ExternalProbe); ok {
		return x.ExternalProbe
	}
	return nil
}

func (m *ProbeDef) GetUdpProbe() *proto8.ProbeConf {
	if x, ok := m.GetProbe().(*ProbeDef_UdpProbe); ok {
		return x.UdpProbe
	}
	return nil
}

func (m *ProbeDef) GetUdpListenerProbe() *proto9.ProbeConf {
	if x, ok := m.GetProbe().(*ProbeDef_UdpListenerProbe); ok {
		return x.UdpListenerProbe
	}
	return nil
}

func (m *ProbeDef) GetUserDefinedProbe() string {
	if x, ok := m.GetProbe().(*ProbeDef_UserDefinedProbe); ok {
		return x.UserDefinedProbe
	}
	return ""
}

func (m *ProbeDef) GetDebugOptions() *DebugOptions {
	if m != nil {
		return m.DebugOptions
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ProbeDef) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ProbeDef_OneofMarshaler, _ProbeDef_OneofUnmarshaler, _ProbeDef_OneofSizer, []interface{}{
		(*ProbeDef_SourceIp)(nil),
		(*ProbeDef_SourceInterface)(nil),
		(*ProbeDef_PingProbe)(nil),
		(*ProbeDef_HttpProbe)(nil),
		(*ProbeDef_DnsProbe)(nil),
		(*ProbeDef_ExternalProbe)(nil),
		(*ProbeDef_UdpProbe)(nil),
		(*ProbeDef_UdpListenerProbe)(nil),
		(*ProbeDef_UserDefinedProbe)(nil),
	}
}

func _ProbeDef_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ProbeDef)
	// source_ip_config
	switch x := m.SourceIpConfig.(type) {
	case *ProbeDef_SourceIp:
		_ = b.EncodeVarint(10<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.SourceIp)
	case *ProbeDef_SourceInterface:
		_ = b.EncodeVarint(11<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.SourceInterface)
	case nil:
	default:
		return fmt.Errorf("ProbeDef.SourceIpConfig has unexpected type %T", x)
	}
	// probe
	switch x := m.Probe.(type) {
	case *ProbeDef_PingProbe:
		_ = b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingProbe); err != nil {
			return err
		}
	case *ProbeDef_HttpProbe:
		_ = b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpProbe); err != nil {
			return err
		}
	case *ProbeDef_DnsProbe:
		_ = b.EncodeVarint(22<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DnsProbe); err != nil {
			return err
		}
	case *ProbeDef_ExternalProbe:
		_ = b.EncodeVarint(23<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExternalProbe); err != nil {
			return err
		}
	case *ProbeDef_UdpProbe:
		_ = b.EncodeVarint(24<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UdpProbe); err != nil {
			return err
		}
	case *ProbeDef_UdpListenerProbe:
		_ = b.EncodeVarint(25<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UdpListenerProbe); err != nil {
			return err
		}
	case *ProbeDef_UserDefinedProbe:
		_ = b.EncodeVarint(99<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.UserDefinedProbe)
	case nil:
	default:
		return fmt.Errorf("ProbeDef.Probe has unexpected type %T", x)
	}
	return nil
}

func _ProbeDef_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ProbeDef)
	switch tag {
	case 10: // source_ip_config.source_ip
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.SourceIpConfig = &ProbeDef_SourceIp{x}
		return true, err
	case 11: // source_ip_config.source_interface
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.SourceIpConfig = &ProbeDef_SourceInterface{x}
		return true, err
	case 20: // probe.ping_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto4.ProbeConf)
		err := b.DecodeMessage(msg)
		m.Probe = &ProbeDef_PingProbe{msg}
		return true, err
	case 21: // probe.http_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto5.ProbeConf)
		err := b.DecodeMessage(msg)
		m.Probe = &ProbeDef_HttpProbe{msg}
		return true, err
	case 22: // probe.dns_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto6.ProbeConf)
		err := b.DecodeMessage(msg)
		m.Probe = &ProbeDef_DnsProbe{msg}
		return true, err
	case 23: // probe.external_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto7.ProbeConf)
		err := b.DecodeMessage(msg)
		m.Probe = &ProbeDef_ExternalProbe{msg}
		return true, err
	case 24: // probe.udp_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto8.ProbeConf)
		err := b.DecodeMessage(msg)
		m.Probe = &ProbeDef_UdpProbe{msg}
		return true, err
	case 25: // probe.udp_listener_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto9.ProbeConf)
		err := b.DecodeMessage(msg)
		m.Probe = &ProbeDef_UdpListenerProbe{msg}
		return true, err
	case 99: // probe.user_defined_probe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Probe = &ProbeDef_UserDefinedProbe{x}
		return true, err
	default:
		return false, nil
	}
}

func _ProbeDef_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ProbeDef)
	// source_ip_config
	switch x := m.SourceIpConfig.(type) {
	case *ProbeDef_SourceIp:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.SourceIp)))
		n += len(x.SourceIp)
	case *ProbeDef_SourceInterface:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.SourceInterface)))
		n += len(x.SourceInterface)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// probe
	switch x := m.Probe.(type) {
	case *ProbeDef_PingProbe:
		s := proto.Size(x.PingProbe)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProbeDef_HttpProbe:
		s := proto.Size(x.HttpProbe)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProbeDef_DnsProbe:
		s := proto.Size(x.DnsProbe)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProbeDef_ExternalProbe:
		s := proto.Size(x.ExternalProbe)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProbeDef_UdpProbe:
		s := proto.Size(x.UdpProbe)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProbeDef_UdpListenerProbe:
		s := proto.Size(x.UdpListenerProbe)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProbeDef_UserDefinedProbe:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(len(x.UserDefinedProbe)))
		n += len(x.UserDefinedProbe)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DebugOptions struct {
	// Whether to log metrics or not.
	LogMetrics           *bool    `protobuf:"varint,1,opt,name=log_metrics,json=logMetrics" json:"log_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugOptions) Reset()         { *m = DebugOptions{} }
func (m *DebugOptions) String() string { return proto.CompactTextString(m) }
func (*DebugOptions) ProtoMessage()    {}
func (*DebugOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_4592f190be15414f, []int{1}
}
func (m *DebugOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugOptions.Unmarshal(m, b)
}
func (m *DebugOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugOptions.Marshal(b, m, deterministic)
}
func (dst *DebugOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugOptions.Merge(dst, src)
}
func (m *DebugOptions) XXX_Size() int {
	return xxx_messageInfo_DebugOptions.Size(m)
}
func (m *DebugOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DebugOptions proto.InternalMessageInfo

func (m *DebugOptions) GetLogMetrics() bool {
	if m != nil && m.LogMetrics != nil {
		return *m.LogMetrics
	}
	return false
}

func init() {
	proto.RegisterType((*ProbeDef)(nil), "cloudprober.probes.ProbeDef")
	proto.RegisterType((*DebugOptions)(nil), "cloudprober.probes.DebugOptions")
	proto.RegisterEnum("cloudprober.probes.ProbeDef_Type", ProbeDef_Type_name, ProbeDef_Type_value)
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/probes/proto/config.proto", fileDescriptor_config_4592f190be15414f)
}

var fileDescriptor_config_4592f190be15414f = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x51, 0xaf, 0xdb, 0x34,
	0x14, 0xc7, 0x97, 0xde, 0x76, 0x37, 0x71, 0xdb, 0x11, 0x99, 0x0d, 0xb2, 0x2b, 0xa1, 0x85, 0x4a,
	0x40, 0x06, 0x52, 0x7a, 0xa9, 0x98, 0xd0, 0xee, 0x03, 0xb0, 0x2d, 0x81, 0x5b, 0xa9, 0x6b, 0xab,
	0xb4, 0x17, 0xc1, 0x53, 0x94, 0xc6, 0x6e, 0x67, 0x29, 0x75, 0xa2, 0xc4, 0x9e, 0xd6, 0xb7, 0x7e,
	0x39, 0x24, 0x3e, 0x16, 0x72, 0x6c, 0xef, 0xb6, 0x23, 0x77, 0xaa, 0xf6, 0x14, 0xfb, 0x9c, 0xff,
	0xf9, 0xf9, 0x1c, 0x1f, 0x9f, 0x80, 0x67, 0x1b, 0xc2, 0xde, 0xf0, 0x95, 0x9f, 0xe6, 0xdb, 0xe1,
	0x0e, 0xbf, 0x63, 0xc3, 0x34, 0xcb, 0x39, 0x2a, 0xca, 0x7c, 0x85, 0xcb, 0x61, 0xfd, 0xa9, 0xc4,
	0x87, 0xe5, 0xc3, 0x34, 0xa7, 0x6b, 0xb2, 0xf1, 0xeb, 0x0d, 0x84, 0x07, 0x32, 0x5f, 0xca, 0x2e,
	0x7e, 0xfa, 0x18, 0x6a, 0x8b, 0x59, 0x49, 0x52, 0xcd, 0x42, 0xa4, 0x62, 0x92, 0x74, 0xf1, 0xfc,
	0x84, 0x04, 0x10, 0x6d, 0x4a, 0xe2, 0xe2, 0x97, 0x13, 0x42, 0xf1, 0x3b, 0x86, 0x4b, 0x9a, 0x64,
	0x4d, 0xf1, 0x57, 0x27, 0xc4, 0xbf, 0x61, 0xac, 0xf8, 0xd4, 0xd8, 0x82, 0xd0, 0x4d, 0x53, 0xec,
	0x29, 0x25, 0x73, 0xd4, 0x78, 0xec, 0x8b, 0xd3, 0x42, 0x33, 0x52, 0x31, 0x4c, 0xa5, 0xe9, 0x43,
	0xc4, 0xcf, 0x1f, 0x43, 0xb0, 0xa4, 0xdc, 0x60, 0xa6, 0x6f, 0x5b, 0xed, 0x4e, 0x49, 0xfb, 0x6d,
	0x92, 0x11, 0x94, 0xb0, 0xbc, 0x6c, 0xea, 0xd4, 0xe0, 0x1f, 0x0b, 0x98, 0x73, 0x21, 0x0c, 0xf0,
	0x1a, 0x42, 0xd0, 0xa6, 0xc9, 0x16, 0x3b, 0x86, 0xdb, 0xf2, 0xac, 0xa8, 0x5e, 0xc3, 0x67, 0xa0,
	0xcd, 0x76, 0x05, 0x76, 0x5a, 0x6e, 0xcb, 0x7b, 0x30, 0xfa, 0xda, 0xff, 0xff, 0xf3, 0xf2, 0x75,
	0xbc, 0xbf, 0xdc, 0x15, 0x38, 0xaa, 0xe5, 0xf0, 0x11, 0xb8, 0x5f, 0x72, 0x1a, 0xe7, 0xd4, 0x39,
	0x73, 0x0d, 0xcf, 0x8a, 0x3a, 0x25, 0xa7, 0x33, 0x0a, 0x9f, 0x82, 0x3e, 0xa1, 0x0c, 0x97, 0x6f,
	0x93, 0x2c, 0xde, 0x56, 0x38, 0x75, 0xda, 0xae, 0xe1, 0x75, 0xae, 0xda, 0xa3, 0xcb, 0xcb, 0xcb,
	0xa8, 0xa7, 0x5d, 0xaf, 0x2b, 0x9c, 0xc2, 0xef, 0x40, 0x8f, 0x91, 0x2d, 0xce, 0x39, 0x93, 0xca,
	0x8e, 0x54, 0xfe, 0x28, 0x94, 0x5d, 0xe5, 0xa9, 0x85, 0xcf, 0xc1, 0xb9, 0xba, 0x0e, 0xe7, 0xbe,
	0xdb, 0xf2, 0xba, 0xa3, 0x27, 0x47, 0x49, 0xea, 0xab, 0x5a, 0xca, 0x6f, 0x80, 0xd7, 0x91, 0xd6,
	0xc3, 0x09, 0x78, 0x98, 0x25, 0x0c, 0xd3, 0x74, 0x17, 0x8b, 0x87, 0x5f, 0x92, 0x15, 0x67, 0x24,
	0xa7, 0xce, 0xb9, 0x6b, 0x78, 0xdd, 0xd1, 0xe3, 0x23, 0x8e, 0x9a, 0x13, 0x3f, 0x20, 0x15, 0x8b,
	0x3e, 0x57, 0x61, 0xc1, 0x41, 0x14, 0xfc, 0x06, 0xf4, 0x34, 0x8d, 0x53, 0xc2, 0x1c, 0x53, 0x54,
	0x7e, 0xd5, 0xe2, 0x55, 0xd4, 0x55, 0xf6, 0x1b, 0x4a, 0x18, 0xfc, 0x15, 0x58, 0xef, 0x7b, 0xe2,
	0x58, 0xee, 0x99, 0xd7, 0xfd, 0xe0, 0x5a, 0x6f, 0x3b, 0xe6, 0xff, 0xa9, 0x97, 0xd1, 0x6d, 0x0c,
	0xfc, 0x0a, 0x58, 0x55, 0xce, 0xcb, 0x14, 0xc7, 0xa4, 0x70, 0x80, 0x38, 0xe4, 0xfa, 0x5e, 0x64,
	0x4a, 0xd3, 0xb8, 0x80, 0x3f, 0x00, 0x5b, 0xbb, 0xc5, 0x7d, 0xae, 0x93, 0x14, 0x3b, 0x5d, 0xa5,
	0xfa, 0x4c, 0xa9, 0xb4, 0x03, 0xbe, 0x02, 0x40, 0x0c, 0x43, 0x5c, 0x1f, 0xed, 0x3c, 0xac, 0xeb,
	0x1e, 0x34, 0x35, 0x59, 0xa8, 0x64, 0xa7, 0x5f, 0xe5, 0x74, 0x7d, 0x6d, 0x44, 0x96, 0xb0, 0xd4,
	0x06, 0x01, 0x11, 0xd3, 0xa8, 0x20, 0x8f, 0xee, 0x86, 0x08, 0xd5, 0x31, 0x44, 0x58, 0x24, 0xe4,
	0x37, 0x60, 0x21, 0x5a, 0x29, 0xc6, 0x17, 0x35, 0xa3, 0xf1, 0xb5, 0x21, 0x5a, 0x1d, 0x21, 0x4c,
	0x44, 0x2b, 0x49, 0x98, 0x81, 0x07, 0xfa, 0xa7, 0xa2, 0x30, 0x5f, 0xd6, 0x98, 0x6f, 0x9b, 0x30,
	0x5a, 0x79, 0xc4, 0xea, 0x6b, 0xeb, 0xfb, 0x94, 0x38, 0xd2, 0x65, 0x39, 0x77, 0xa7, 0xc4, 0xd1,
	0x71, 0x55, 0x26, 0x47, 0xaa, 0xa8, 0xbf, 0x01, 0x14, 0x04, 0x3d, 0xf5, 0x0a, 0xf5, 0xb8, 0x46,
	0x3d, 0xbd, 0x03, 0xa5, 0xc5, 0x47, 0x48, 0x9b, 0xa3, 0x62, 0xa2, 0x1c, 0x12, 0xed, 0x03, 0xc8,
	0x2b, 0x5c, 0xc6, 0x08, 0xaf, 0x09, 0xc5, 0x48, 0xa1, 0xd3, 0xba, 0xd1, 0x42, 0x5f, 0xe1, 0x32,
	0x90, 0x2e, 0xa9, 0x0f, 0x41, 0x1f, 0xe1, 0x15, 0xdf, 0xc4, 0x79, 0x21, 0x5e, 0x6b, 0xe5, 0xa0,
	0x3a, 0x0b, 0xb7, 0x29, 0x8b, 0x40, 0x08, 0x67, 0x52, 0x17, 0xf5, 0xd0, 0xc1, 0x6e, 0xb0, 0x05,
	0x6d, 0x31, 0xe6, 0xd0, 0x04, 0xed, 0xf9, 0x78, 0xfa, 0x87, 0x7d, 0x4f, 0xac, 0xae, 0x97, 0xcb,
	0xb9, 0x6d, 0xc0, 0x73, 0x70, 0x16, 0x4c, 0x17, 0x76, 0x0b, 0xf6, 0x80, 0x19, 0xfe, 0xb5, 0x0c,
	0xa3, 0xe9, 0x8b, 0x89, 0x7d, 0x26, 0xcc, 0x37, 0xc1, 0xdc, 0x6e, 0x43, 0x1b, 0xf4, 0x6e, 0x82,
	0x79, 0x3c, 0x19, 0x2f, 0x96, 0xe1, 0x34, 0x8c, 0xec, 0x0e, 0xec, 0x03, 0x4b, 0x08, 0xa7, 0x8b,
	0xf1, 0x6c, 0x6a, 0xaf, 0x6a, 0xc1, 0x22, 0x8c, 0xe2, 0x20, 0xfc, 0x7d, 0x3c, 0x0d, 0x03, 0x3b,
	0xfd, 0xde, 0x32, 0xff, 0x35, 0xec, 0xfd, 0x7e, 0xbf, 0x6f, 0xbd, 0x84, 0xb7, 0xef, 0xba, 0x88,
	0xe5, 0x4f, 0xec, 0xe5, 0x39, 0xe8, 0xd4, 0x29, 0x0f, 0x86, 0xa0, 0x77, 0x98, 0x34, 0x7c, 0x02,
	0xba, 0x59, 0xbe, 0x89, 0xd5, 0xd0, 0x3a, 0x86, 0x6b, 0x78, 0x66, 0x04, 0xb2, 0x7c, 0xf3, 0x5a,
	0x5a, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xc5, 0xa5, 0xb9, 0x5f, 0x07, 0x00, 0x00,
}
