// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/probes/ping/proto/config.proto

package cloudprober_probes_ping

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ProbeConf struct {
	// Set the source address to send packets from, either by providing an address
	// or a network interface.
	// NOTE: Setting source address using these fields is now deprecated and will
	// be removed after release v0.10.2. To set source, please modify the outer
	// probe configuration.
	// probe {
	//   type: PING
	//   source_interface: eth1
	//   ping_probe {}
	// }
	//
	// Types that are valid to be assigned to Source:
	//	*ProbeConf_SourceIp
	//	*ProbeConf_SourceInterface
	Source isProbeConf_Source `protobuf_oneof:"source"`
	// Packets per probe
	PacketsPerProbe *int32 `protobuf:"varint,6,opt,name=packets_per_probe,json=packetsPerProbe,def=2" json:"packets_per_probe,omitempty"`
	// How long to wait between two packets to the same target
	PacketsIntervalMsec *int32 `protobuf:"varint,7,opt,name=packets_interval_msec,json=packetsIntervalMsec,def=25" json:"packets_interval_msec,omitempty"`
	// Export stats after these many probes
	StatsExportInterval *int32 `protobuf:"varint,8,opt,name=stats_export_interval,json=statsExportInterval,def=5" json:"stats_export_interval,omitempty"`
	// Resolve targets after these many probes
	ResolveTargetsInterval *int32 `protobuf:"varint,9,opt,name=resolve_targets_interval,json=resolveTargetsInterval,def=5" json:"resolve_targets_interval,omitempty"`
	// Ping payload size in bytes. It cannot be smaller than 8, number of bytes
	// required for the nanoseconds timestamp.
	PayloadSize *int32 `protobuf:"varint,10,opt,name=payload_size,json=payloadSize,def=56" json:"payload_size,omitempty"`
	// IP protocol version
	IpVersion *int32 `protobuf:"varint,11,opt,name=ip_version,json=ipVersion,def=4" json:"ip_version,omitempty"`
	// Use datagram socket for ICMP.
	// This option enables unprivileged pings (that is, you don't require root
	// privilege to send ICMP packets). Note that most of the Linux distributions
	// don't allow unprivileged pings by default. To enable unprivileged pings on
	// some Linux distributions, you may need to run the following command:
	//     sudo sysctl -w net.ipv4.ping_group_range="0 <large valid group id>"
	// net.ipv4.ping_group_range system setting takes two integers that specify
	// the group id range that is allowed to execute the unprivileged pings. Note
	// that the same setting (with ipv4 in the path) applies to IPv6 as well.
	UseDatagramSocket *bool `protobuf:"varint,12,opt,name=use_datagram_socket,json=useDatagramSocket,def=1" json:"use_datagram_socket,omitempty"`
	// Disable integrity checks. To detect data courruption in the network, we
	// craft the outgoing ICMP packet payload in a certain format and verify that
	// the reply payload matches the same format.
	DisableIntegrityCheck *bool    `protobuf:"varint,13,opt,name=disable_integrity_check,json=disableIntegrityCheck,def=0" json:"disable_integrity_check,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ProbeConf) Reset()         { *m = ProbeConf{} }
func (m *ProbeConf) String() string { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()    {}
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_dc1fba43bc8185b0, []int{0}
}
func (m *ProbeConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf.Unmarshal(m, b)
}
func (m *ProbeConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf.Marshal(b, m, deterministic)
}
func (dst *ProbeConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf.Merge(dst, src)
}
func (m *ProbeConf) XXX_Size() int {
	return xxx_messageInfo_ProbeConf.Size(m)
}
func (m *ProbeConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf proto.InternalMessageInfo

const Default_ProbeConf_PacketsPerProbe int32 = 2
const Default_ProbeConf_PacketsIntervalMsec int32 = 25
const Default_ProbeConf_StatsExportInterval int32 = 5
const Default_ProbeConf_ResolveTargetsInterval int32 = 5
const Default_ProbeConf_PayloadSize int32 = 56
const Default_ProbeConf_IpVersion int32 = 4
const Default_ProbeConf_UseDatagramSocket bool = true
const Default_ProbeConf_DisableIntegrityCheck bool = false

type isProbeConf_Source interface {
	isProbeConf_Source()
}

type ProbeConf_SourceIp struct {
	SourceIp string `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,oneof"`
}
type ProbeConf_SourceInterface struct {
	SourceInterface string `protobuf:"bytes,4,opt,name=source_interface,json=sourceInterface,oneof"`
}

func (*ProbeConf_SourceIp) isProbeConf_Source()        {}
func (*ProbeConf_SourceInterface) isProbeConf_Source() {}

func (m *ProbeConf) GetSource() isProbeConf_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ProbeConf) GetSourceIp() string {
	if x, ok := m.GetSource().(*ProbeConf_SourceIp); ok {
		return x.SourceIp
	}
	return ""
}

func (m *ProbeConf) GetSourceInterface() string {
	if x, ok := m.GetSource().(*ProbeConf_SourceInterface); ok {
		return x.SourceInterface
	}
	return ""
}

func (m *ProbeConf) GetPacketsPerProbe() int32 {
	if m != nil && m.PacketsPerProbe != nil {
		return *m.PacketsPerProbe
	}
	return Default_ProbeConf_PacketsPerProbe
}

func (m *ProbeConf) GetPacketsIntervalMsec() int32 {
	if m != nil && m.PacketsIntervalMsec != nil {
		return *m.PacketsIntervalMsec
	}
	return Default_ProbeConf_PacketsIntervalMsec
}

func (m *ProbeConf) GetStatsExportInterval() int32 {
	if m != nil && m.StatsExportInterval != nil {
		return *m.StatsExportInterval
	}
	return Default_ProbeConf_StatsExportInterval
}

func (m *ProbeConf) GetResolveTargetsInterval() int32 {
	if m != nil && m.ResolveTargetsInterval != nil {
		return *m.ResolveTargetsInterval
	}
	return Default_ProbeConf_ResolveTargetsInterval
}

func (m *ProbeConf) GetPayloadSize() int32 {
	if m != nil && m.PayloadSize != nil {
		return *m.PayloadSize
	}
	return Default_ProbeConf_PayloadSize
}

func (m *ProbeConf) GetIpVersion() int32 {
	if m != nil && m.IpVersion != nil {
		return *m.IpVersion
	}
	return Default_ProbeConf_IpVersion
}

func (m *ProbeConf) GetUseDatagramSocket() bool {
	if m != nil && m.UseDatagramSocket != nil {
		return *m.UseDatagramSocket
	}
	return Default_ProbeConf_UseDatagramSocket
}

func (m *ProbeConf) GetDisableIntegrityCheck() bool {
	if m != nil && m.DisableIntegrityCheck != nil {
		return *m.DisableIntegrityCheck
	}
	return Default_ProbeConf_DisableIntegrityCheck
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ProbeConf) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ProbeConf_OneofMarshaler, _ProbeConf_OneofUnmarshaler, _ProbeConf_OneofSizer, []interface{}{
		(*ProbeConf_SourceIp)(nil),
		(*ProbeConf_SourceInterface)(nil),
	}
}

func _ProbeConf_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ProbeConf)
	// source
	switch x := m.Source.(type) {
	case *ProbeConf_SourceIp:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.SourceIp)
	case *ProbeConf_SourceInterface:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.SourceInterface)
	case nil:
	default:
		return fmt.Errorf("ProbeConf.Source has unexpected type %T", x)
	}
	return nil
}

func _ProbeConf_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ProbeConf)
	switch tag {
	case 3: // source.source_ip
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Source = &ProbeConf_SourceIp{x}
		return true, err
	case 4: // source.source_interface
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Source = &ProbeConf_SourceInterface{x}
		return true, err
	default:
		return false, nil
	}
}

func _ProbeConf_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ProbeConf)
	// source
	switch x := m.Source.(type) {
	case *ProbeConf_SourceIp:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.SourceIp)))
		n += len(x.SourceIp)
	case *ProbeConf_SourceInterface:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.SourceInterface)))
		n += len(x.SourceInterface)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ProbeConf)(nil), "cloudprober.probes.ping.ProbeConf")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/probes/ping/proto/config.proto", fileDescriptor_config_dc1fba43bc8185b0)
}

var fileDescriptor_config_dc1fba43bc8185b0 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x6b, 0xdb, 0x30,
	0x18, 0x86, 0xe7, 0xf5, 0xc7, 0x6c, 0xb5, 0xa3, 0xab, 0x42, 0x56, 0x5d, 0x06, 0x66, 0x30, 0x08,
	0x8c, 0xd9, 0x50, 0xea, 0x1e, 0x32, 0x76, 0x59, 0x37, 0x58, 0x0e, 0x83, 0xa2, 0x8e, 0x5d, 0x85,
	0x22, 0x7f, 0x76, 0x45, 0x1d, 0x4b, 0x48, 0x72, 0x68, 0xfa, 0xa7, 0xef, 0x34, 0x2c, 0xc9, 0x21,
	0x27, 0x5b, 0xdf, 0xf3, 0xbc, 0x7a, 0x6d, 0x3e, 0xb4, 0x6c, 0xa5, 0x7b, 0x1c, 0xd6, 0x85, 0x50,
	0x9b, 0x72, 0x07, 0xcf, 0xae, 0x14, 0x9d, 0x1a, 0x6a, 0x6d, 0xd4, 0x1a, 0x4c, 0xe9, 0x1f, 0xb6,
	0xd4, 0xb2, 0x6f, 0xc7, 0x77, 0xa7, 0x4a, 0xa1, 0xfa, 0x46, 0xb6, 0x85, 0x3f, 0xe0, 0xab, 0x03,
	0xb7, 0x08, 0x6e, 0x31, 0xba, 0x1f, 0xff, 0x1d, 0xa1, 0xec, 0x7e, 0x3c, 0xdf, 0xa9, 0xbe, 0xc1,
	0x1f, 0x50, 0x66, 0xd5, 0x60, 0x04, 0x30, 0xa9, 0xc9, 0x51, 0x9e, 0x2c, 0xb2, 0x5f, 0xaf, 0x68,
	0x1a, 0x46, 0x2b, 0x8d, 0x3f, 0xa3, 0x77, 0x13, 0xee, 0x1d, 0x98, 0x86, 0x0b, 0x20, 0xc7, 0xd1,
	0xba, 0x88, 0xd6, 0x04, 0xf0, 0x17, 0x74, 0xa9, 0xb9, 0x78, 0x02, 0x67, 0x99, 0x06, 0xc3, 0x7c,
	0x29, 0x39, 0xcd, 0x93, 0xc5, 0xc9, 0x32, 0xb9, 0xa6, 0x17, 0x91, 0xdd, 0x83, 0xf1, 0xf5, 0xf8,
	0x16, 0xcd, 0x27, 0xdd, 0x5f, 0xbe, 0xe5, 0x1d, 0xdb, 0x58, 0x10, 0xe4, 0x8d, 0x8f, 0xbc, 0xbe,
	0xae, 0xe8, 0x2c, 0x0a, 0xab, 0xc8, 0x7f, 0x5b, 0x10, 0xb8, 0x42, 0x73, 0xeb, 0xb8, 0xb3, 0x0c,
	0x9e, 0xb5, 0x32, 0x6e, 0x1f, 0x26, 0x69, 0xa8, 0xaa, 0xe8, 0xcc, 0xf3, 0x9f, 0x1e, 0x4f, 0x51,
	0xfc, 0x15, 0x11, 0x03, 0x56, 0x75, 0x5b, 0x60, 0x8e, 0x9b, 0xf6, 0xb0, 0x96, 0x64, 0x53, 0xf2,
	0x7d, 0x54, 0xfe, 0x04, 0x63, 0x1f, 0xfe, 0x84, 0xce, 0x35, 0xdf, 0x75, 0x8a, 0xd7, 0xcc, 0xca,
	0x17, 0x20, 0x28, 0x7c, 0x62, 0x75, 0x4b, 0xcf, 0xe2, 0xfc, 0x41, 0xbe, 0x00, 0xce, 0x11, 0x92,
	0x9a, 0x6d, 0xc1, 0x58, 0xa9, 0x7a, 0x72, 0x16, 0x6e, 0xbd, 0xa1, 0x99, 0xd4, 0x7f, 0xc3, 0x0c,
	0xdf, 0xa0, 0xd9, 0x60, 0x81, 0xd5, 0xdc, 0xf1, 0xd6, 0xf0, 0x0d, 0xb3, 0x6a, 0xfc, 0x41, 0x72,
	0x9e, 0x27, 0x8b, 0x74, 0x79, 0xec, 0xcc, 0x00, 0xf4, 0x72, 0xb0, 0xf0, 0x23, 0xf2, 0x07, 0x8f,
	0xf1, 0x37, 0x74, 0x55, 0x4b, 0xcb, 0xd7, 0x5d, 0xd8, 0x43, 0x6b, 0xa4, 0xdb, 0x31, 0xf1, 0x08,
	0xe2, 0x89, 0xbc, 0xf5, 0xc9, 0x93, 0x86, 0x77, 0x16, 0xe8, 0x3c, 0x5a, 0xab, 0x49, 0xba, 0x1b,
	0x9d, 0xef, 0x29, 0x3a, 0x0d, 0xbb, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xc4, 0x8f, 0x2d,
	0x52, 0x02, 0x00, 0x00,
}
