// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/targets/rtc/proto/config.proto

package cloudprober_targets_rtc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// TargetsConf represents listing targets from a key/val set stored in the RTC
// API under a certain provided configuration. It always only lists the keys
// (hostnames) and provides a resolver which will resolve to a single tag. This
// can be used as a kind of drop-in replacement for GCE Instances when that
// would not be possible. For example, one could set "resolve_tag" to "ip", and
// this lister will now list all VM names, with a resolver that resolves those
// names to their ip addresses.
//
// For more information on RTC see
// https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/
//
// It is assumed that this is being curated, and indeed can be controlled with
// settings in a cloudprober configuration.  See
// cloudprober/config/config.proto.
type TargetsConf struct {
	// Config-name to list hosts from.
	Cfg *string `protobuf:"bytes,1,opt,name=cfg" json:"cfg,omitempty"`
	// Expiration time in ms for RTC variables. Variables older will be ignored.
	ExpireMsec *int32 `protobuf:"varint,2,opt,name=expire_msec,json=expireMsec,def=30000" json:"expire_msec,omitempty"`
	// Which address tag to resolve a hostname to. Hosts report multiple addresses
	// for themselves, each with a "tag" (like "PUBLIC_IP" or "PRIVATE_IP"). For
	// more information, see the "tag" field of the RtcTargetInfo.Address message.
	ResolveTag *string `protobuf:"bytes,3,opt,name=resolve_tag,json=resolveTag" json:"resolve_tag,omitempty"`
	// groups is a list of groups that should be included by the lister. Hosts can
	// assign themselves a set "groups" such as "Zone1" or "HasMultiNIC". If this
	// field is set, then we will filter out hosts that don't have a group that
	// matches any groups listed here. If groups is not set, no filtering will
	// occure.
	//
	// For more information, see the "groups" field of the RtcTargetInfo message.
	//
	// Example :
	//   Host1 has group "G1" and "G2"
	//   Host2 has groups "G2" and "G3"
	//   Host3 has no groups.
	//   The following table shows values for groups and which hosts will be
	//   listed.
	//   groups      | Listed Hosts
	//   ------------|--------------------
	//   ["G1"]      | Host1
	//   ["G2"]      | Host1, Host2
	//   ["G1","G3"] | Host1, Host2
	//   ["G4"]      | None
	//   []          | Host1, Host2, Host3
	Groups []string `protobuf:"bytes,4,rep,name=groups" json:"groups,omitempty"`
	// How often targets should be evaluated. Any number less than or equal to 0
	// will result in no target caching (targets will be reevaluated on demand).
	ReEvalSec *int32 `protobuf:"varint,6,opt,name=re_eval_sec,json=reEvalSec,def=0" json:"re_eval_sec,omitempty"`
	// The alphanumeric ID of the project which this instance is member of
	// (not project number)
	// e.g. bbmc-cloudprober-instance-cxkdsa123
	ProjectId            []string `protobuf:"bytes,7,rep,name=project_id,json=projectId" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetsConf) Reset()         { *m = TargetsConf{} }
func (m *TargetsConf) String() string { return proto.CompactTextString(m) }
func (*TargetsConf) ProtoMessage()    {}
func (*TargetsConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_4f92f50c4460978b, []int{0}
}
func (m *TargetsConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetsConf.Unmarshal(m, b)
}
func (m *TargetsConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetsConf.Marshal(b, m, deterministic)
}
func (dst *TargetsConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetsConf.Merge(dst, src)
}
func (m *TargetsConf) XXX_Size() int {
	return xxx_messageInfo_TargetsConf.Size(m)
}
func (m *TargetsConf) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetsConf.DiscardUnknown(m)
}

var xxx_messageInfo_TargetsConf proto.InternalMessageInfo

const Default_TargetsConf_ExpireMsec int32 = 30000
const Default_TargetsConf_ReEvalSec int32 = 0

func (m *TargetsConf) GetCfg() string {
	if m != nil && m.Cfg != nil {
		return *m.Cfg
	}
	return ""
}

func (m *TargetsConf) GetExpireMsec() int32 {
	if m != nil && m.ExpireMsec != nil {
		return *m.ExpireMsec
	}
	return Default_TargetsConf_ExpireMsec
}

func (m *TargetsConf) GetResolveTag() string {
	if m != nil && m.ResolveTag != nil {
		return *m.ResolveTag
	}
	return ""
}

func (m *TargetsConf) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *TargetsConf) GetReEvalSec() int32 {
	if m != nil && m.ReEvalSec != nil {
		return *m.ReEvalSec
	}
	return Default_TargetsConf_ReEvalSec
}

func (m *TargetsConf) GetProjectId() []string {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

func init() {
	proto.RegisterType((*TargetsConf)(nil), "cloudprober.targets.rtc.TargetsConf")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/targets/rtc/proto/config.proto", fileDescriptor_config_4f92f50c4460978b)
}

var fileDescriptor_config_4f92f50c4460978b = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0x3f, 0x4f, 0xb4, 0x40,
	0x10, 0xc6, 0xc3, 0xcb, 0x7b, 0x67, 0x18, 0x1a, 0xb3, 0x85, 0xd2, 0x18, 0xd1, 0xc2, 0x50, 0xb1,
	0x24, 0x76, 0xd7, 0x1a, 0x0b, 0x0b, 0x1b, 0xbc, 0x9e, 0xec, 0x0d, 0xc3, 0x8a, 0xe1, 0x6e, 0x36,
	0xb3, 0x0b, 0x39, 0xbf, 0x9e, 0x9f, 0xcc, 0xc0, 0x51, 0xd8, 0xcd, 0xef, 0x99, 0xe7, 0x0f, 0xec,
	0x6c, 0x1f, 0x3e, 0xc7, 0x43, 0x89, 0x7c, 0xd4, 0xdf, 0x74, 0x0e, 0x1a, 0x07, 0x1e, 0x5b, 0x27,
	0x7c, 0x20, 0xd1, 0xc1, 0x88, 0xa5, 0xe0, 0xb5, 0x04, 0xd4, 0x4e, 0x38, 0xb0, 0x46, 0x3e, 0x75,
	0xbd, 0x2d, 0x17, 0x50, 0xb7, 0x7f, 0xbc, 0xe5, 0xea, 0x2d, 0x25, 0xe0, 0xe3, 0x4f, 0x04, 0xe9,
	0xfe, 0xc2, 0x2f, 0x7c, 0xea, 0xd4, 0x35, 0xc4, 0xd8, 0xd9, 0x2c, 0xca, 0xa3, 0x22, 0xa9, 0xe7,
	0x53, 0x3d, 0x41, 0x4a, 0x67, 0xd7, 0x0b, 0x35, 0x47, 0x4f, 0x98, 0xfd, 0xcb, 0xa3, 0x62, 0xb3,
	0xdb, 0x3c, 0x57, 0x55, 0x55, 0xd5, 0x70, 0xf9, 0xbc, 0x7b, 0x42, 0x75, 0x0f, 0xa9, 0x90, 0xe7,
	0x61, 0xa2, 0x26, 0x18, 0x9b, 0xc5, 0x4b, 0x03, 0xac, 0xd2, 0xde, 0x58, 0x75, 0x03, 0x5b, 0x2b,
	0x3c, 0x3a, 0x9f, 0xfd, 0xcf, 0xe3, 0x22, 0xa9, 0x57, 0x52, 0x0f, 0x73, 0xb0, 0xa1, 0xc9, 0x0c,
	0xcd, 0x3c, 0xb0, 0x5d, 0x06, 0xa2, 0xaa, 0x4e, 0x84, 0x5e, 0x27, 0x33, 0x7c, 0x10, 0xaa, 0x3b,
	0x00, 0x27, 0xfc, 0x45, 0x18, 0x9a, 0xbe, 0xcd, 0xae, 0x96, 0x78, 0xb2, 0x2a, 0x6f, 0xed, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x26, 0x57, 0x75, 0x1a, 0x01, 0x00, 0x00,
}
