// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/validators/http/proto/config.proto

package cloudprober_validators_http

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Validator struct {
	// Comma-separated list of success status codes and code ranges.
	// Example: success_stauts_codes: 200-299,301,302
	SuccessStatusCodes *string `protobuf:"bytes,1,opt,name=success_status_codes,json=successStatusCodes" json:"success_status_codes,omitempty"`
	// Comma-separated list of failure status codes and code ranges. If there is
	// an overloap between success and failure status codes, failure status codes
	// take precedence over success status codes.
	FailureStatusCodes   *string  `protobuf:"bytes,2,opt,name=failure_status_codes,json=failureStatusCodes" json:"failure_status_codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_a2faaff689ff95e0, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (dst *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(dst, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetSuccessStatusCodes() string {
	if m != nil && m.SuccessStatusCodes != nil {
		return *m.SuccessStatusCodes
	}
	return ""
}

func (m *Validator) GetFailureStatusCodes() string {
	if m != nil && m.FailureStatusCodes != nil {
		return *m.FailureStatusCodes
	}
	return ""
}

func init() {
	proto.RegisterType((*Validator)(nil), "cloudprober.validators.http.Validator")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/validators/http/proto/config.proto", fileDescriptor_config_a2faaff689ff95e0)
}

var fileDescriptor_config_a2faaff689ff95e0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8b, 0x31, 0xae, 0xc2, 0x30,
	0x10, 0x05, 0x95, 0xdf, 0x25, 0xa5, 0xf5, 0x0b, 0x24, 0x1a, 0x44, 0x45, 0xe5, 0xe5, 0x04, 0x34,
	0xdc, 0x00, 0x24, 0xda, 0xc8, 0x59, 0x3b, 0x89, 0x25, 0xc3, 0x5a, 0xde, 0x35, 0x82, 0xdb, 0x23,
	0x87, 0x20, 0x42, 0xf9, 0xde, 0xcc, 0x34, 0x87, 0xc1, 0xcb, 0x98, 0x3b, 0x8d, 0x74, 0x85, 0xa7,
	0x7b, 0x08, 0x60, 0xa0, 0x6c, 0x63, 0xa2, 0xce, 0x25, 0xb8, 0x9b, 0xe0, 0xad, 0x11, 0x4a, 0x0c,
	0xa3, 0x48, 0x84, 0x98, 0x48, 0x08, 0x90, 0x6e, 0xbd, 0x1f, 0xf4, 0x34, 0xd4, 0x7a, 0xe1, 0xeb,
	0xaf, 0xaf, 0x8b, 0xbf, 0xa5, 0xa6, 0xbe, 0x7c, 0x2e, 0xb5, 0x6f, 0xfe, 0x39, 0x23, 0x3a, 0xe6,
	0x96, 0xc5, 0x48, 0xe6, 0x16, 0xc9, 0x3a, 0x5e, 0x55, 0x9b, 0x6a, 0x57, 0x9f, 0xd4, 0xcc, 0xce,
	0x13, 0x3a, 0x16, 0x52, 0x8a, 0xde, 0xf8, 0x90, 0x93, 0xfb, 0x2d, 0xfe, 0xde, 0xc5, 0xcc, 0x16,
	0xc5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x39, 0x1c, 0x74, 0xd2, 0xce, 0x00, 0x00, 0x00,
}
