// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/servers/proto/config.proto

package cloudprober_servers

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import proto3 "github.com/yext/cloudprober/servers/grpc/proto"
import proto1 "github.com/yext/cloudprober/servers/http/proto"
import proto2 "github.com/yext/cloudprober/servers/udp/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ServerDef_Type int32

const (
	ServerDef_HTTP ServerDef_Type = 0
	ServerDef_UDP  ServerDef_Type = 1
	ServerDef_GRPC ServerDef_Type = 2
)

var ServerDef_Type_name = map[int32]string{
	0: "HTTP",
	1: "UDP",
	2: "GRPC",
}
var ServerDef_Type_value = map[string]int32{
	"HTTP": 0,
	"UDP":  1,
	"GRPC": 2,
}

func (x ServerDef_Type) Enum() *ServerDef_Type {
	p := new(ServerDef_Type)
	*p = x
	return p
}
func (x ServerDef_Type) String() string {
	return proto.EnumName(ServerDef_Type_name, int32(x))
}
func (x *ServerDef_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerDef_Type_value, data, "ServerDef_Type")
	if err != nil {
		return err
	}
	*x = ServerDef_Type(value)
	return nil
}
func (ServerDef_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_de8807504167a6f9, []int{0, 0}
}

type ServerDef struct {
	Type *ServerDef_Type `protobuf:"varint,1,req,name=type,enum=cloudprober.servers.ServerDef_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Server:
	//	*ServerDef_HttpServer
	//	*ServerDef_UdpServer
	//	*ServerDef_GrpcServer
	Server               isServerDef_Server `protobuf_oneof:"server"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ServerDef) Reset()         { *m = ServerDef{} }
func (m *ServerDef) String() string { return proto.CompactTextString(m) }
func (*ServerDef) ProtoMessage()    {}
func (*ServerDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_de8807504167a6f9, []int{0}
}
func (m *ServerDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerDef.Unmarshal(m, b)
}
func (m *ServerDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerDef.Marshal(b, m, deterministic)
}
func (dst *ServerDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerDef.Merge(dst, src)
}
func (m *ServerDef) XXX_Size() int {
	return xxx_messageInfo_ServerDef.Size(m)
}
func (m *ServerDef) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerDef.DiscardUnknown(m)
}

var xxx_messageInfo_ServerDef proto.InternalMessageInfo

type isServerDef_Server interface {
	isServerDef_Server()
}

type ServerDef_HttpServer struct {
	HttpServer *proto1.ServerConf `protobuf:"bytes,2,opt,name=http_server,json=httpServer,oneof"`
}
type ServerDef_UdpServer struct {
	UdpServer *proto2.ServerConf `protobuf:"bytes,3,opt,name=udp_server,json=udpServer,oneof"`
}
type ServerDef_GrpcServer struct {
	GrpcServer *proto3.ServerConf `protobuf:"bytes,4,opt,name=grpc_server,json=grpcServer,oneof"`
}

func (*ServerDef_HttpServer) isServerDef_Server() {}
func (*ServerDef_UdpServer) isServerDef_Server()  {}
func (*ServerDef_GrpcServer) isServerDef_Server() {}

func (m *ServerDef) GetServer() isServerDef_Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ServerDef) GetType() ServerDef_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ServerDef_HTTP
}

func (m *ServerDef) GetHttpServer() *proto1.ServerConf {
	if x, ok := m.GetServer().(*ServerDef_HttpServer); ok {
		return x.HttpServer
	}
	return nil
}

func (m *ServerDef) GetUdpServer() *proto2.ServerConf {
	if x, ok := m.GetServer().(*ServerDef_UdpServer); ok {
		return x.UdpServer
	}
	return nil
}

func (m *ServerDef) GetGrpcServer() *proto3.ServerConf {
	if x, ok := m.GetServer().(*ServerDef_GrpcServer); ok {
		return x.GrpcServer
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerDef) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServerDef_OneofMarshaler, _ServerDef_OneofUnmarshaler, _ServerDef_OneofSizer, []interface{}{
		(*ServerDef_HttpServer)(nil),
		(*ServerDef_UdpServer)(nil),
		(*ServerDef_GrpcServer)(nil),
	}
}

func _ServerDef_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServerDef)
	// server
	switch x := m.Server.(type) {
	case *ServerDef_HttpServer:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpServer); err != nil {
			return err
		}
	case *ServerDef_UdpServer:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UdpServer); err != nil {
			return err
		}
	case *ServerDef_GrpcServer:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GrpcServer); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerDef.Server has unexpected type %T", x)
	}
	return nil
}

func _ServerDef_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServerDef)
	switch tag {
	case 2: // server.http_server
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto1.ServerConf)
		err := b.DecodeMessage(msg)
		m.Server = &ServerDef_HttpServer{msg}
		return true, err
	case 3: // server.udp_server
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto2.ServerConf)
		err := b.DecodeMessage(msg)
		m.Server = &ServerDef_UdpServer{msg}
		return true, err
	case 4: // server.grpc_server
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto3.ServerConf)
		err := b.DecodeMessage(msg)
		m.Server = &ServerDef_GrpcServer{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerDef_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServerDef)
	// server
	switch x := m.Server.(type) {
	case *ServerDef_HttpServer:
		s := proto.Size(x.HttpServer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerDef_UdpServer:
		s := proto.Size(x.UdpServer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerDef_GrpcServer:
		s := proto.Size(x.GrpcServer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ServerDef)(nil), "cloudprober.servers.ServerDef")
	proto.RegisterEnum("cloudprober.servers.ServerDef_Type", ServerDef_Type_name, ServerDef_Type_value)
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/servers/proto/config.proto", fileDescriptor_config_de8807504167a6f9)
}

var fileDescriptor_config_de8807504167a6f9 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xd7, 0xae, 0xe8, 0xf6, 0x15, 0xa4, 0xc4, 0xcb, 0xf0, 0x34, 0x36, 0x0f, 0x3b, 0x25,
	0xb0, 0x83, 0x82, 0xde, 0x5c, 0xa1, 0x3b, 0x96, 0x5a, 0xcf, 0xc2, 0x9a, 0xb4, 0x1b, 0xe8, 0x12,
	0xb2, 0x44, 0xec, 0x6f, 0xf4, 0x4f, 0xc9, 0xd7, 0x6c, 0x43, 0x46, 0x90, 0x1e, 0xf3, 0xf2, 0xbc,
	0x0f, 0xef, 0x17, 0x78, 0x68, 0x76, 0x66, 0x6b, 0x37, 0xb4, 0x92, 0x9f, 0xac, 0x15, 0xdf, 0x86,
	0x55, 0x1f, 0xd2, 0x72, 0xa5, 0xe5, 0x46, 0x68, 0x76, 0x10, 0xfa, 0x4b, 0xe8, 0x03, 0x53, 0x5a,
	0x1a, 0xc9, 0x2a, 0xb9, 0xaf, 0x77, 0x0d, 0xed, 0x1e, 0xe4, 0xf6, 0x0f, 0x47, 0x8f, 0xdc, 0xdd,
	0x73, 0x1f, 0x59, 0xa3, 0x55, 0xe5, 0x31, 0xf6, 0x2b, 0x6f, 0x8d, 0x51, 0xbe, 0xf2, 0x53, 0x9f,
	0xb2, 0xe5, 0xbe, 0xee, 0xec, 0x27, 0x84, 0xf1, 0x6b, 0x87, 0xa4, 0xa2, 0x26, 0x8f, 0x10, 0x99,
	0x56, 0x89, 0x49, 0x30, 0x0d, 0x17, 0x37, 0xcb, 0x39, 0xf5, 0xdc, 0x49, 0xcf, 0x34, 0x2d, 0x5b,
	0x25, 0x8a, 0xae, 0x40, 0x32, 0x88, 0x71, 0xdd, 0xbb, 0x83, 0x26, 0xe1, 0x34, 0x58, 0xc4, 0xcb,
	0x7b, 0x6f, 0x1f, 0xb9, 0xa3, 0x64, 0x25, 0xf7, 0xf5, 0x7a, 0x50, 0x00, 0x46, 0x2e, 0x21, 0x29,
	0x80, 0xe5, 0x67, 0xcf, 0xb0, 0xf3, 0xf8, 0x77, 0x58, 0x7e, 0xa1, 0x19, 0x5b, 0x7e, 0xb2, 0x64,
	0x10, 0xe3, 0x4f, 0x9f, 0x34, 0xd1, 0x3f, 0x73, 0x90, 0xbb, 0x98, 0x83, 0x91, 0x4b, 0x66, 0x73,
	0x88, 0xf0, 0x4a, 0x32, 0x82, 0x68, 0x5d, 0x96, 0x79, 0x32, 0x20, 0xd7, 0x30, 0x7c, 0x4b, 0xf3,
	0x24, 0xc0, 0x28, 0x2b, 0xf2, 0x55, 0x12, 0xbe, 0x8c, 0xe0, 0xca, 0xd9, 0x7e, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x4e, 0x53, 0x52, 0x1c, 0x51, 0x02, 0x00, 0x00,
}
