// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/surfacers/postgres/proto/config.proto

package cloudprober_surfacer_postgres

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SurfacerConf struct {
	ConnectionString     *string  `protobuf:"bytes,1,req,name=connection_string,json=connectionString" json:"connection_string,omitempty"`
	MetricsTableName     *string  `protobuf:"bytes,2,req,name=metrics_table_name,json=metricsTableName" json:"metrics_table_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurfacerConf) Reset()         { *m = SurfacerConf{} }
func (m *SurfacerConf) String() string { return proto.CompactTextString(m) }
func (*SurfacerConf) ProtoMessage()    {}
func (*SurfacerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_aebcb087f9c8c02d, []int{0}
}
func (m *SurfacerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurfacerConf.Unmarshal(m, b)
}
func (m *SurfacerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurfacerConf.Marshal(b, m, deterministic)
}
func (dst *SurfacerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurfacerConf.Merge(dst, src)
}
func (m *SurfacerConf) XXX_Size() int {
	return xxx_messageInfo_SurfacerConf.Size(m)
}
func (m *SurfacerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_SurfacerConf.DiscardUnknown(m)
}

var xxx_messageInfo_SurfacerConf proto.InternalMessageInfo

func (m *SurfacerConf) GetConnectionString() string {
	if m != nil && m.ConnectionString != nil {
		return *m.ConnectionString
	}
	return ""
}

func (m *SurfacerConf) GetMetricsTableName() string {
	if m != nil && m.MetricsTableName != nil {
		return *m.MetricsTableName
	}
	return ""
}

func init() {
	proto.RegisterType((*SurfacerConf)(nil), "cloudprober.surfacer.postgres.SurfacerConf")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/surfacers/postgres/proto/config.proto", fileDescriptor_config_aebcb087f9c8c02d)
}

var fileDescriptor_config_aebcb087f9c8c02d = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8b, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0xf9, 0xba, 0x7d, 0xc1, 0x41, 0x33, 0x75, 0x11, 0xc4, 0x49, 0x50, 0x92, 0xdf, 0x20,
	0xee, 0x0e, 0xd6, 0xbd, 0xa4, 0xf1, 0x1a, 0x03, 0xcd, 0x5d, 0xb9, 0x5c, 0x41, 0xff, 0xbd, 0x58,
	0x5b, 0x74, 0x7c, 0x9f, 0xe7, 0x7d, 0xd4, 0x31, 0x44, 0xb9, 0x0f, 0x8d, 0xf1, 0x94, 0xec, 0x13,
	0x1e, 0x62, 0x7d, 0x47, 0xc3, 0xad, 0x67, 0x6a, 0x80, 0x6d, 0x1e, 0xb8, 0x75, 0x1e, 0x38, 0xdb,
	0x9e, 0xb2, 0x04, 0x86, 0x6c, 0x7b, 0x26, 0x21, 0xeb, 0x09, 0xdb, 0x18, 0xcc, 0x38, 0xf4, 0xfa,
	0x27, 0x31, 0x73, 0x62, 0xe6, 0x62, 0x1b, 0xd5, 0xa2, 0x9a, 0xe0, 0x89, 0xb0, 0xd5, 0x7b, 0xb5,
	0xf2, 0x84, 0x08, 0x5e, 0x22, 0x61, 0x9d, 0x85, 0x23, 0x86, 0xf2, 0x6f, 0x53, 0xec, 0xfe, 0x2f,
	0xcb, 0xaf, 0xa8, 0x46, 0xae, 0x0f, 0x4a, 0x27, 0x10, 0x8e, 0x3e, 0xd7, 0xe2, 0x9a, 0x0e, 0x6a,
	0x74, 0x09, 0xca, 0xe2, 0xf3, 0x9e, 0xcc, 0xf5, 0x2d, 0xce, 0x2e, 0xc1, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0x59, 0xc3, 0x19, 0xcd, 0x00, 0x00, 0x00,
}
