// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/surfacers/prometheus/proto/config.proto

package cloudprober_surfacer_prometheus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SurfacerConf struct {
	// How many metrics entries (EventMetrics) to buffer. Incoming metrics
	// processing is paused while serving data to prometheus. This buffer is to
	// make writes to prometheus surfacer non-blocking.
	MetricsBufferSize *int64 `protobuf:"varint,1,opt,name=metrics_buffer_size,json=metricsBufferSize,def=10000" json:"metrics_buffer_size,omitempty"`
	// Whether to include timestamps in metrics. If enabled (default) each metric
	// string includes the metric timestamp as recorded in the EventMetric.
	// Prometheus associates the scraped values with this timestamp. If disabled,
	// i.e. timestamps are not exported, prometheus associates scraped values with
	// scrape timestamp.
	IncludeTimestamp *bool `protobuf:"varint,2,opt,name=include_timestamp,json=includeTimestamp,def=1" json:"include_timestamp,omitempty"`
	// URL that prometheus scrapes metrics from.
	MetricsUrl           *string  `protobuf:"bytes,3,opt,name=metrics_url,json=metricsUrl,def=/metrics" json:"metrics_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurfacerConf) Reset()         { *m = SurfacerConf{} }
func (m *SurfacerConf) String() string { return proto.CompactTextString(m) }
func (*SurfacerConf) ProtoMessage()    {}
func (*SurfacerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b8ba0e6f80272a68, []int{0}
}
func (m *SurfacerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurfacerConf.Unmarshal(m, b)
}
func (m *SurfacerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurfacerConf.Marshal(b, m, deterministic)
}
func (dst *SurfacerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurfacerConf.Merge(dst, src)
}
func (m *SurfacerConf) XXX_Size() int {
	return xxx_messageInfo_SurfacerConf.Size(m)
}
func (m *SurfacerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_SurfacerConf.DiscardUnknown(m)
}

var xxx_messageInfo_SurfacerConf proto.InternalMessageInfo

const Default_SurfacerConf_MetricsBufferSize int64 = 10000
const Default_SurfacerConf_IncludeTimestamp bool = true
const Default_SurfacerConf_MetricsUrl string = "/metrics"

func (m *SurfacerConf) GetMetricsBufferSize() int64 {
	if m != nil && m.MetricsBufferSize != nil {
		return *m.MetricsBufferSize
	}
	return Default_SurfacerConf_MetricsBufferSize
}

func (m *SurfacerConf) GetIncludeTimestamp() bool {
	if m != nil && m.IncludeTimestamp != nil {
		return *m.IncludeTimestamp
	}
	return Default_SurfacerConf_IncludeTimestamp
}

func (m *SurfacerConf) GetMetricsUrl() string {
	if m != nil && m.MetricsUrl != nil {
		return *m.MetricsUrl
	}
	return Default_SurfacerConf_MetricsUrl
}

func init() {
	proto.RegisterType((*SurfacerConf)(nil), "cloudprober.surfacer.prometheus.SurfacerConf")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/surfacers/prometheus/proto/config.proto", fileDescriptor_config_b8ba0e6f80272a68)
}

var fileDescriptor_config_b8ba0e6f80272a68 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0x0a, 0x52, 0x31, 0x0c, 0x34, 0x2c, 0xd9, 0x88, 0x98, 0xc2, 0x12, 0xbb, 0x03,
	0x4b, 0x46, 0xfa, 0x06, 0x29, 0xcc, 0x51, 0xe3, 0x9e, 0x5b, 0x4b, 0x76, 0x1c, 0x9d, 0xef, 0x24,
	0xe8, 0xeb, 0xf0, 0xa2, 0x48, 0x91, 0x23, 0xba, 0xfd, 0xf7, 0xff, 0xdf, 0xa7, 0x93, 0xbb, 0x93,
	0xa3, 0x33, 0x0f, 0x8d, 0x89, 0x41, 0xfd, 0xc0, 0x37, 0x29, 0xe3, 0x23, 0x1f, 0x27, 0x8c, 0x03,
	0xa0, 0x4a, 0x8c, 0xf6, 0x60, 0x00, 0x93, 0x9a, 0x30, 0x06, 0xa0, 0x33, 0xf0, 0x1c, 0x29, 0x2a,
	0x13, 0x47, 0xeb, 0x4e, 0xcd, 0x7c, 0x14, 0x2f, 0x57, 0x52, 0xb3, 0x48, 0xcd, 0xbf, 0xf3, 0xfa,
	0x2b, 0xe4, 0xe3, 0x3e, 0xf7, 0xbb, 0x38, 0xda, 0xe2, 0x5d, 0x3e, 0x07, 0x20, 0x74, 0x26, 0xf5,
	0x03, 0x5b, 0x0b, 0xd8, 0x27, 0x77, 0x81, 0x52, 0x54, 0xa2, 0x5e, 0xb5, 0x77, 0x5b, 0xad, 0xb5,
	0xee, 0x36, 0x99, 0xf8, 0x98, 0x81, 0xbd, 0xbb, 0x40, 0xb1, 0x95, 0x1b, 0x37, 0x1a, 0xcf, 0x47,
	0xe8, 0xc9, 0x05, 0x48, 0x74, 0x08, 0x53, 0x79, 0x53, 0x89, 0x7a, 0xdd, 0xde, 0x12, 0x32, 0x74,
	0x4f, 0x79, 0xfe, 0x5c, 0xd6, 0xe2, 0x4d, 0x3e, 0x2c, 0x9f, 0x18, 0x7d, 0xb9, 0xaa, 0x44, 0x7d,
	0xdf, 0xae, 0x55, 0xee, 0x3a, 0x99, 0xc3, 0x17, 0xfa, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7,
	0x8c, 0xe9, 0x35, 0x0c, 0x01, 0x00, 0x00,
}
