// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/probes/udp/proto/config.proto

package cloudprober_probes_udp

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ProbeConf struct {
	// Export stats after these many milliseconds
	StatsExportIntervalMsec *int32 `protobuf:"varint,2,opt,name=stats_export_interval_msec,json=statsExportIntervalMsec,def=10000" json:"stats_export_interval_msec,omitempty"`
	// Port to send UDP Ping to (UDP Echo).  Should be same as
	// ProberConfig.udp_echo_server_port.
	// TODO(_): Can we just read this from ProberConfig?
	Port *int32 `protobuf:"varint,3,opt,name=port,def=31122" json:"port,omitempty"`
	// Number of sending side ports to use.
	NumTxPorts *int32 `protobuf:"varint,4,opt,name=num_tx_ports,json=numTxPorts,def=16" json:"num_tx_ports,omitempty"`
	// message max to account for MTU.
	MaxLength *int32 `protobuf:"varint,5,opt,name=max_length,json=maxLength,def=1300" json:"max_length,omitempty"`
	// IP proto: v4|v6. Temporary workaround till we add support in base probe proto.
	IpVersion *int32 `protobuf:"varint,6,opt,name=ip_version,json=ipVersion,def=4" json:"ip_version,omitempty"`
	// Changes the exported monitoring streams to be per port:
	// 1. Changes the streams names to total-per-port, success-per-port etc.
	// 2. Adds src_port and dst_port as stream labels.
	// Note that the field name is experimental and may change in the future.
	ExportMetricsByPort *bool `protobuf:"varint,7,opt,name=export_metrics_by_port,json=exportMetricsByPort,def=0" json:"export_metrics_by_port,omitempty"`
	// Whether to use all transmit ports per probe, per target.
	// Default is to probe each target once per probe and round-robin through the
	// source ports.
	// Setting this field to true changes the behavior to send traffic from all
	// ports to all targets in each probe.
	// For example, if num_tx_ports is set to 16, in every probe cycle, we'll send
	// 16 packets to every target (1 per tx port).
	// Note that setting this field to true will increase the probe traffic.
	UseAllTxPortsPerProbe *bool    `protobuf:"varint,8,opt,name=use_all_tx_ports_per_probe,json=useAllTxPortsPerProbe,def=0" json:"use_all_tx_ports_per_probe,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ProbeConf) Reset()         { *m = ProbeConf{} }
func (m *ProbeConf) String() string { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()    {}
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_221fdc570b3da996, []int{0}
}
func (m *ProbeConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf.Unmarshal(m, b)
}
func (m *ProbeConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf.Marshal(b, m, deterministic)
}
func (dst *ProbeConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf.Merge(dst, src)
}
func (m *ProbeConf) XXX_Size() int {
	return xxx_messageInfo_ProbeConf.Size(m)
}
func (m *ProbeConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf proto.InternalMessageInfo

const Default_ProbeConf_StatsExportIntervalMsec int32 = 10000
const Default_ProbeConf_Port int32 = 31122
const Default_ProbeConf_NumTxPorts int32 = 16
const Default_ProbeConf_MaxLength int32 = 1300
const Default_ProbeConf_IpVersion int32 = 4
const Default_ProbeConf_ExportMetricsByPort bool = false
const Default_ProbeConf_UseAllTxPortsPerProbe bool = false

func (m *ProbeConf) GetStatsExportIntervalMsec() int32 {
	if m != nil && m.StatsExportIntervalMsec != nil {
		return *m.StatsExportIntervalMsec
	}
	return Default_ProbeConf_StatsExportIntervalMsec
}

func (m *ProbeConf) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return Default_ProbeConf_Port
}

func (m *ProbeConf) GetNumTxPorts() int32 {
	if m != nil && m.NumTxPorts != nil {
		return *m.NumTxPorts
	}
	return Default_ProbeConf_NumTxPorts
}

func (m *ProbeConf) GetMaxLength() int32 {
	if m != nil && m.MaxLength != nil {
		return *m.MaxLength
	}
	return Default_ProbeConf_MaxLength
}

func (m *ProbeConf) GetIpVersion() int32 {
	if m != nil && m.IpVersion != nil {
		return *m.IpVersion
	}
	return Default_ProbeConf_IpVersion
}

func (m *ProbeConf) GetExportMetricsByPort() bool {
	if m != nil && m.ExportMetricsByPort != nil {
		return *m.ExportMetricsByPort
	}
	return Default_ProbeConf_ExportMetricsByPort
}

func (m *ProbeConf) GetUseAllTxPortsPerProbe() bool {
	if m != nil && m.UseAllTxPortsPerProbe != nil {
		return *m.UseAllTxPortsPerProbe
	}
	return Default_ProbeConf_UseAllTxPortsPerProbe
}

func init() {
	proto.RegisterType((*ProbeConf)(nil), "cloudprober.probes.udp.ProbeConf")
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/probes/udp/proto/config.proto", fileDescriptor_config_221fdc570b3da996)
}

var fileDescriptor_config_221fdc570b3da996 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x4b, 0x6b, 0x32, 0x31,
	0x14, 0x06, 0x60, 0xf4, 0x73, 0xbe, 0x6a, 0xe8, 0x2a, 0xa5, 0x36, 0x75, 0x25, 0x6d, 0x17, 0xae,
	0xe6, 0xa2, 0xa5, 0x50, 0x57, 0xad, 0xa5, 0x8b, 0x42, 0x05, 0x19, 0x4a, 0xb7, 0x61, 0x1c, 0x8f,
	0x1a, 0xc8, 0x8d, 0x5c, 0x64, 0xfc, 0xa1, 0xfd, 0x3f, 0x25, 0x19, 0x29, 0xae, 0x66, 0xce, 0xcb,
	0x13, 0xf2, 0xe6, 0xa0, 0xe7, 0x1d, 0x73, 0x7b, 0xbf, 0x4e, 0x6b, 0x25, 0xb2, 0x23, 0x34, 0x2e,
	0xab, 0xb9, 0xf2, 0x1b, 0x6d, 0xd4, 0x1a, 0x4c, 0x16, 0x3f, 0x36, 0xf3, 0x1b, 0x1d, 0x7e, 0x9d,
	0xca, 0x6a, 0x25, 0xb7, 0x6c, 0x97, 0xc6, 0x01, 0x0f, 0xcf, 0x68, 0xda, 0xd2, 0xd4, 0x6f, 0xf4,
	0xdd, 0x4f, 0x17, 0x0d, 0x56, 0x61, 0x7c, 0x53, 0x72, 0x8b, 0x17, 0x68, 0x64, 0x5d, 0xe5, 0x2c,
	0x85, 0x46, 0x2b, 0xe3, 0x28, 0x93, 0x0e, 0xcc, 0xa1, 0xe2, 0x54, 0x58, 0xa8, 0x49, 0x77, 0xdc,
	0x99, 0x24, 0xf3, 0xa4, 0xc8, 0xf3, 0x3c, 0x2f, 0x6f, 0x22, 0x7c, 0x8f, 0xee, 0xe3, 0xc4, 0x96,
	0x16, 0x6a, 0x7c, 0x8b, 0x7a, 0x21, 0x23, 0xff, 0x5a, 0x3d, 0x2b, 0x8a, 0xe9, 0xb4, 0x8c, 0x11,
	0x7e, 0x40, 0x97, 0xd2, 0x0b, 0xea, 0x1a, 0x1a, 0x46, 0x4b, 0x7a, 0x91, 0x74, 0x8b, 0xa7, 0x12,
	0x49, 0x2f, 0xbe, 0x9a, 0x55, 0x48, 0xf1, 0x3d, 0x42, 0xa2, 0x6a, 0x28, 0x07, 0xb9, 0x73, 0x7b,
	0x92, 0x44, 0xd3, 0x2b, 0x66, 0x79, 0x5e, 0x0e, 0x44, 0xd5, 0x7c, 0xc6, 0x18, 0x8f, 0x11, 0x62,
	0x9a, 0x1e, 0xc0, 0x58, 0xa6, 0x24, 0xf9, 0x1f, 0x51, 0xe7, 0xb1, 0x1c, 0x30, 0xfd, 0xdd, 0x66,
	0x78, 0x8e, 0x86, 0xa7, 0x57, 0x08, 0x70, 0x86, 0xd5, 0x96, 0xae, 0x8f, 0xf1, 0x5e, 0x72, 0x31,
	0xee, 0x4c, 0xfa, 0xf3, 0x64, 0x5b, 0x71, 0x0b, 0xe5, 0x55, 0x8b, 0x96, 0xad, 0x59, 0x1c, 0x43,
	0x07, 0xfc, 0x82, 0x46, 0xde, 0x02, 0xad, 0x38, 0xff, 0x2b, 0x4b, 0x35, 0x18, 0x1a, 0x17, 0x47,
	0xfa, 0xe7, 0xe7, 0xaf, 0xbd, 0x85, 0x57, 0xce, 0x4f, 0xe5, 0x57, 0x60, 0xe2, 0x36, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xc7, 0x22, 0x01, 0x23, 0xab, 0x01, 0x00, 0x00,
}
