// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/yext/cloudprober/examples/extensions/myprober/myprobe/myprobe.proto

package myprober

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/yext/cloudprober/probes/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Redis operation
type ProbeConf_Op int32

const (
	ProbeConf_GET    ProbeConf_Op = 0
	ProbeConf_SET    ProbeConf_Op = 1
	ProbeConf_DELETE ProbeConf_Op = 2
)

var ProbeConf_Op_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "DELETE",
}
var ProbeConf_Op_value = map[string]int32{
	"GET":    0,
	"SET":    1,
	"DELETE": 2,
}

func (x ProbeConf_Op) Enum() *ProbeConf_Op {
	p := new(ProbeConf_Op)
	*p = x
	return p
}
func (x ProbeConf_Op) String() string {
	return proto.EnumName(ProbeConf_Op_name, int32(x))
}
func (x *ProbeConf_Op) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProbeConf_Op_value, data, "ProbeConf_Op")
	if err != nil {
		return err
	}
	*x = ProbeConf_Op(value)
	return nil
}
func (ProbeConf_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_myprobe_113ceb5db8106c32, []int{0, 0}
}

type ProbeConf struct {
	Op *ProbeConf_Op `protobuf:"varint,1,req,name=op,enum=myprober.ProbeConf_Op" json:"op,omitempty"`
	// Key and value for the redis operation
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeConf) Reset()         { *m = ProbeConf{} }
func (m *ProbeConf) String() string { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()    {}
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_myprobe_113ceb5db8106c32, []int{0}
}
func (m *ProbeConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf.Unmarshal(m, b)
}
func (m *ProbeConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf.Marshal(b, m, deterministic)
}
func (dst *ProbeConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf.Merge(dst, src)
}
func (m *ProbeConf) XXX_Size() int {
	return xxx_messageInfo_ProbeConf.Size(m)
}
func (m *ProbeConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf proto.InternalMessageInfo

func (m *ProbeConf) GetOp() ProbeConf_Op {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ProbeConf_GET
}

func (m *ProbeConf) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProbeConf) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

var E_RedisProbe = &proto.ExtensionDesc{
	ExtendedType:  (*proto1.ProbeDef)(nil),
	ExtensionType: (*ProbeConf)(nil),
	Field:         200,
	Name:          "myprober.redis_probe",
	Tag:           "bytes,200,opt,name=redis_probe,json=redisProbe",
	Filename:      "github.com/yext/cloudprober/examples/extensions/myprober/myprobe/myprobe.proto",
}

func init() {
	proto.RegisterType((*ProbeConf)(nil), "myprober.ProbeConf")
	proto.RegisterEnum("myprober.ProbeConf_Op", ProbeConf_Op_name, ProbeConf_Op_value)
	proto.RegisterExtension(E_RedisProbe)
}

func init() {
	proto.RegisterFile("github.com/yext/cloudprober/examples/extensions/myprober/myprobe/myprobe.proto", fileDescriptor_myprobe_113ceb5db8106c32)
}

var fileDescriptor_myprobe_113ceb5db8106c32 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xcd, 0x16, 0x3f, 0x32, 0x05, 0x09, 0xab, 0x48, 0x10, 0x0f, 0x21, 0x07, 0xc9, 0x69,
	0x17, 0x0a, 0x5e, 0xbc, 0xda, 0xc5, 0x8b, 0x58, 0x49, 0x73, 0x97, 0x36, 0x9d, 0xd4, 0x60, 0x92,
	0x59, 0xb2, 0x89, 0x24, 0x27, 0xff, 0x9e, 0x3f, 0x4b, 0xb2, 0x69, 0xc4, 0x83, 0x78, 0x9a, 0x77,
	0x78, 0x77, 0x9f, 0x79, 0xe0, 0x79, 0x9f, 0x37, 0x6f, 0xed, 0x56, 0xa4, 0x54, 0xca, 0x1e, 0xbb,
	0x46, 0xa6, 0x05, 0xb5, 0x3b, 0x5d, 0xd3, 0x16, 0x6b, 0x89, 0xdd, 0xa6, 0xd4, 0x05, 0x1a, 0x89,
	0x5d, 0x83, 0x95, 0xc9, 0xa9, 0x32, 0xb2, 0xec, 0x0f, 0xe5, 0x21, 0x4c, 0x53, 0xe8, 0x9a, 0x1a,
	0xe2, 0x67, 0x53, 0x7f, 0x7d, 0xf7, 0x1f, 0xd9, 0x0e, 0x23, 0xed, 0x1f, 0x99, 0x52, 0x95, 0xe5,
	0xfb, 0x11, 0x10, 0x7e, 0x82, 0xfb, 0x32, 0x94, 0x0f, 0x54, 0x65, 0xfc, 0x16, 0x18, 0x69, 0xdf,
	0x09, 0x58, 0x74, 0xbe, 0xb8, 0x12, 0x13, 0x5a, 0xfc, 0x3c, 0x10, 0x2b, 0x1d, 0x33, 0xd2, 0xdc,
	0x83, 0xd9, 0x3b, 0xf6, 0x3e, 0x0b, 0x58, 0xe4, 0xc6, 0x43, 0xe4, 0x97, 0x70, 0xfc, 0xb1, 0x29,
	0x5a, 0xf4, 0x67, 0x81, 0x13, 0xb9, 0xf1, 0xb8, 0x84, 0x21, 0xb0, 0x95, 0xe6, 0xa7, 0x30, 0x7b,
	0x54, 0x89, 0x77, 0x34, 0x84, 0xb5, 0x4a, 0x3c, 0x87, 0x03, 0x9c, 0x2c, 0xd5, 0x93, 0x4a, 0x94,
	0xc7, 0xee, 0xd7, 0x30, 0xaf, 0x71, 0x97, 0x9b, 0x57, 0x7b, 0x8c, 0xdf, 0x88, 0x5f, 0xde, 0x62,
	0xf4, 0x1e, 0x05, 0x96, 0x98, 0xf9, 0x5f, 0x4e, 0xe0, 0x44, 0xf3, 0xc5, 0xc5, 0x1f, 0x6e, 0x31,
	0x58, 0x8c, 0xdd, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x84, 0x11, 0x6c, 0x10, 0x67, 0x01, 0x00,
	0x00,
}
